export type AppointmentSettingProvider = {
  name: string;
  price: string;
  hasPublicPrice: boolean;
  model: string;
  contractTerm: string;
  channels: string[];
  qualification: string;
  sourceUrl: string;
  sourceLabel: string;
  lastChecked: string;
};

const LAST_CHECKED = "2026-08-23";

export const APPOINTMENT_SETTING_PROVIDERS: AppointmentSettingProvider[] = [
  {
    name: "Abstrakt Marketing Group",
    price: "Starter $5,250; Standard $7,250; Advanced $9,250. The checked page does not state the billing period.",
    hasPublicPrice: true,
    model: "Tiered package",
    contractTerm: "Not publicly stated",
    channels: ["Phone", "Email", "LinkedIn", "Direct mail"],
    qualification: "Company fit, decision authority, current vendor, contract timing, readiness, and clear agreement to meet.",
    sourceUrl: "https://www.abstraktmg.com/b2b-appointment-setting/",
    sourceLabel: "Appointment setting service page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "Belkins",
    price: "From $5,000 average starter price. The checked page does not state the billing period.",
    hasPublicPrice: true,
    model: "Custom package",
    contractTerm: "Not publicly stated",
    channels: ["Three channels; names not stated on checked page"],
    qualification: "Manual lead validation against the buyer's qualification criteria, plus appointment booking and no-show recovery.",
    sourceUrl: "https://belkins.io/appointment-setting",
    sourceLabel: "Appointment setting service page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "Callbox",
    price: "Not publicly stated",
    hasPublicPrice: false,
    model: "Subscription or custom quote",
    contractTerm: "Fixed-scope 3, 6, or 12 month programs are described; exact terms depend on the quote.",
    channels: ["Phone", "Email", "LinkedIn", "Web chat"],
    qualification: "Sales-ready opportunity. The checked service page does not publish the complete acceptance rules.",
    sourceUrl: "https://www.callboxinc.com/appointment-setting-lead-generation/",
    sourceLabel: "Appointment setting service page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "CIENCE",
    price: "Not publicly stated",
    hasPublicPrice: false,
    model: "Custom full-service program",
    contractTerm: "Not publicly stated",
    channels: ["Phone", "Email", "Social"],
    qualification: "The checked guide describes assessing need, budget, authority, and timeframe before scheduling.",
    sourceUrl: "https://www.cience.com/blog/appointment-setting-tips-for-b2b-sales/",
    sourceLabel: "Official appointment setting guide",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "Cleverly",
    price: "$697-$2,997 per month, depending on channel mix, targeting, and scope.",
    hasPublicPrice: true,
    model: "Monthly retainer; no pure pay-per-appointment plan",
    contractTerm: "Not publicly stated",
    channels: ["LinkedIn", "Email", "Phone"],
    qualification: "Title, company size, industry, buying authority, and agreed timing factors must clear the filters set at launch.",
    sourceUrl: "https://www.cleverly.co/appointment-setting",
    sourceLabel: "Appointment setting service page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "ColdIQ",
    price: "Not publicly stated",
    hasPublicPrice: false,
    model: "Custom managed service",
    contractTerm: "Not publicly stated",
    channels: ["Not publicly stated on checked page"],
    qualification: "Confirmed meeting with a qualified decision-maker. The exact scoring rules are not published.",
    sourceUrl: "https://coldiq.com/b2b-appointment-setting-service",
    sourceLabel: "Appointment setting service page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "DemandZEN",
    price: "Custom quote",
    hasPublicPrice: false,
    model: "Demand Held performance-based program or managed service",
    contractTerm: "Not publicly stated",
    channels: ["Phone", "Multi-channel; other channels not named"],
    qualification: "Contacts must fit the buyer's target market. The complete acceptance rules are not published.",
    sourceUrl: "https://demandzen.com/b2b-appointment-setting/",
    sourceLabel: "Appointment setting service page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "demandDrive",
    price: "Custom quote",
    hasPublicPrice: false,
    model: "Outcome-based program or standard SDR retainer",
    contractTerm: "Not publicly stated",
    channels: ["Multi-touch, multi-channel; names not stated"],
    qualification: "The buyer defines quality upfront. Meetings must match the ICP and agreed deal-ready criteria.",
    sourceUrl: "https://www.demanddrive.com/services/outsourced-sales-services/b2b-appointment-setting/",
    sourceLabel: "Appointment setting service page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "EBQ",
    price: "Not publicly stated",
    hasPublicPrice: false,
    model: "Priced by full-time or half-time employees",
    contractTerm: "Annual contract, paid monthly",
    channels: ["Phone"],
    qualification: "Target decision-maker reached through a value-based conversation. Full acceptance rules are not published.",
    sourceUrl: "https://ebq.com/ebq-pricing/",
    sourceLabel: "Official pricing page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "Intelemark",
    price: "Not publicly stated for Intelemark's own service",
    hasPublicPrice: false,
    model: "Not publicly stated for Intelemark's own service",
    contractTerm: "Not publicly stated",
    channels: ["Not publicly stated on checked page"],
    qualification: "The official guide recommends written firmographic, decision-maker, meeting-length, and pre-call criteria.",
    sourceUrl: "https://www.intelemark.com/blog/b2b-appointment-setting-pricing-guide-models-costs-and-roi-standards-for-2025/",
    sourceLabel: "Official pricing guide",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "LeadHaste",
    price: "Not publicly stated",
    hasPublicPrice: false,
    model: "Managed outbound system with a performance guarantee",
    contractTerm: "No contract stated on checked page",
    channels: ["Email", "LinkedIn", "Phone"],
    qualification: "Right role, acknowledged problem, genuine interest in a conversation, and a confirmed calendar hold.",
    sourceUrl: "https://leadhaste.com/blog/b2b-appointment-setting-services-guide",
    sourceLabel: "Official qualification guide",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "Leadium",
    price: "$3,500 per month for cold-call-only; $4,000-$5,000 per month for multichannel.",
    hasPublicPrice: true,
    model: "Flat monthly retainer",
    contractTerm: "Month-to-month",
    channels: ["Phone", "Email", "LinkedIn"],
    qualification: "The pricing page says a prospect is qualified when they agree to connect on a sales call.",
    sourceUrl: "https://www.leadium.com/pricing",
    sourceLabel: "Official pricing page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "Leadriver",
    price: "$300-$600 per qualified meeting at steady state, depending on target seniority and industry complexity.",
    hasPublicPrice: true,
    model: "Custom managed multichannel program",
    contractTerm: "Not publicly stated",
    channels: ["Email", "LinkedIn", "Phone"],
    qualification: "Research-first targeting with strict criteria; the complete acceptance rules are set per client and not published.",
    sourceUrl: "https://www.leadriver.io/blog/b2b-appointment-setting-cost-benchmarks",
    sourceLabel: "Official pricing guide",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "MarketJoy",
    price: "Not publicly stated",
    hasPublicPrice: false,
    model: "Custom program",
    contractTerm: "Not publicly stated",
    channels: ["Not publicly stated on checked page"],
    qualification: "Prospects must align with the buyer's ideal customer profile and sales objectives. Full rules are not published.",
    sourceUrl: "https://marketjoy.com/appointment-generation-setting/",
    sourceLabel: "Appointment setting service page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "Martal Group",
    price: "Not publicly stated",
    hasPublicPrice: false,
    model: "Three custom engagement tiers; pricing by request",
    contractTerm: "Not publicly stated",
    channels: ["Email", "LinkedIn", "Phone"],
    qualification: "Targeting, objections, qualification, and scheduling are managed by the provider. Inbound leads use BANT; outbound rules are not fully published.",
    sourceUrl: "https://martal.ca/b2b-appointment-setting/",
    sourceLabel: "Appointment setting service page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "memoryBlue",
    price: "Not publicly stated",
    hasPublicPrice: false,
    model: "Fixed fee, pay-for-performance, or hybrid",
    contractTerm: "Not publicly stated",
    channels: ["Phone", "Email", "LinkedIn"],
    qualification: "Qualified meetings and opportunities; the complete acceptance rules are not published.",
    sourceUrl: "https://memoryblue.com/lead-generation-services/sales-development/",
    sourceLabel: "Sales development service page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "OneAway",
    price: "OS [25] $6,200/month; OS [50] $10,200/month; OS [100] custom plus $300 per qualified meeting.",
    hasPublicPrice: true,
    model: "Monthly coverage tier; performance fee on OS [100]",
    contractTerm: "Month-to-month; 60-day delivery cycles",
    channels: ["Email", "LinkedIn", "Warm phone follow-up"],
    qualification: "Campaigns use buyer-approved leads. The public page does not publish the complete qualified-meeting definition.",
    sourceUrl: "https://oneaway.io/services/done-for-you",
    sourceLabel: "Done-for-you pricing page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "Operatix",
    price: "Not publicly stated",
    hasPublicPrice: false,
    model: "Custom managed service",
    contractTerm: "Not publicly stated",
    channels: ["Personalized multi-touch; channels not named"],
    qualification: "Campaign expectations and reporting are agreed with the buyer. Full acceptance rules are not published.",
    sourceUrl: "https://operatix.net/appointment-setting-uk/",
    sourceLabel: "Appointment setting service page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "Outbound System",
    price: "Not publicly stated for Outbound System's own service",
    hasPublicPrice: false,
    model: "Not publicly stated for Outbound System's own service",
    contractTerm: "Not publicly stated",
    channels: ["Email", "LinkedIn", "Phone"],
    qualification: "The official guide says qualification depends on ICP, industry, and package; complete rules are not published.",
    sourceUrl: "https://outboundsystem.com/blog/b2b-appointment-setting-cost",
    sourceLabel: "Official pricing guide",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "Pearl Lemon Leads",
    price: "From GBP 4,497 per month for appointment setting.",
    hasPublicPrice: true,
    model: "Monthly retainer; quote varies by volume, seniority, and channels",
    contractTerm: "Not publicly stated on the checked appointment setting page",
    channels: ["Phone", "Email", "LinkedIn"],
    qualification: "Company fit, decision-maker relevance, clear business need, meeting intent, and a clean handoff.",
    sourceUrl: "https://pearllemonleads.com/appointment-setting-services-houston-tx/",
    sourceLabel: "Appointment setting service page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "RevBoss",
    price: "$3,500 per month for Core; $4,500+ per month for Full Stack.",
    hasPublicPrice: true,
    model: "Monthly per-seat program",
    contractTerm: "Month-to-month; discounts for 6 or 12 months",
    channels: ["LinkedIn", "Email", "Content", "Events"],
    qualification: "Measures leads and conversations rather than a published billable-meeting definition.",
    sourceUrl: "https://revboss.com/blog/80-20-sales-rule",
    sourceLabel: "Official service and pricing page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "SalesAR",
    price: "Not publicly stated",
    hasPublicPrice: false,
    model: "Custom package",
    contractTerm: "Not publicly stated",
    channels: ["Email", "LinkedIn", "Phone"],
    qualification: "Official material describes human validation for fit, interest, timing, and opportunity. Full acceptance rules are not published.",
    sourceUrl: "https://salesar.io/packages",
    sourceLabel: "Official packages page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "SalesBread",
    price: "$3,000 per month plus a one-time setup fee; setup amount not published.",
    hasPublicPrice: true,
    model: "Monthly done-for-you service",
    contractTerm: "No locked contract",
    channels: ["LinkedIn", "Email"],
    qualification: "Public fit gate: active LinkedIn prospects, more than 200 target companies, and a four-figure product or service.",
    sourceUrl: "https://salesbread.com/done-for-you-lead-generation/",
    sourceLabel: "Done-for-you service page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "SalesCaptain",
    price: "Not publicly stated for SalesCaptain's own service",
    hasPublicPrice: false,
    model: "Custom modular program",
    contractTerm: "Not publicly stated",
    channels: ["Not publicly stated on checked page"],
    qualification: "The official guide requires ICP filtering and recommends measuring show rate, ICP match, and post-meeting stage conversion.",
    sourceUrl: "https://www.salescaptain.io/blog/b2b-appointment-setting-cost-pricing",
    sourceLabel: "Official pricing guide",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "SalesHive",
    price: "Not publicly stated",
    hasPublicPrice: false,
    model: "Custom managed service",
    contractTerm: "No long-term contracts",
    channels: ["Phone", "Email", "Follow-up cadences"],
    qualification: "Only qualified prospects reach the calendar. The checked service page does not publish the complete rules.",
    sourceUrl: "https://saleshive.com/appointment-setting",
    sourceLabel: "Appointment setting service page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "SalesNash",
    price: "Not publicly stated",
    hasPublicPrice: false,
    model: "Custom program",
    contractTerm: "Not publicly stated",
    channels: ["Email", "Phone", "LinkedIn"],
    qualification: "Relevant conversations that fit the buyer's business. The complete acceptance rules are not published.",
    sourceUrl: "https://salesnash.com/appointment-setting/",
    sourceLabel: "Appointment setting service page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "SalesRoads",
    price: "From $9,950 per 4 weeks for Full SDR Appointment Setting.",
    hasPublicPrice: true,
    model: "4-week retainer",
    contractTerm: "Ongoing retainer",
    channels: ["Phone", "Email"],
    qualification: "Qualified appointments and SQLs. The checked pricing page does not publish the complete acceptance rules.",
    sourceUrl: "https://salesroads.com/pricing/",
    sourceLabel: "Official pricing page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "Sopro",
    price: "Not publicly stated",
    hasPublicPrice: false,
    model: "Custom managed service",
    contractTerm: "Not publicly stated",
    channels: ["Multi-channel; names not stated on checked page"],
    qualification: "Prospects must fit the ideal customer profile and be stakeholders ready to engage. Full rules are not published.",
    sourceUrl: "https://sopro.io/solutions/appointment-setting-services/",
    sourceLabel: "Appointment setting service page",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "UnboundB2B",
    price: "Not publicly stated for UnboundB2B's own service",
    hasPublicPrice: false,
    model: "Custom appointment setting and demand generation",
    contractTerm: "Not publicly stated",
    channels: ["Phone", "Email"],
    qualification: "A published case study uses BANT and requires sales-ready decision-makers from key accounts.",
    sourceUrl: "https://www.unboundb2b.com/case-studies/burckhardt-compression-expands-us-market-with-unboundb2b/",
    sourceLabel: "Official appointment setting case study",
    lastChecked: LAST_CHECKED,
  },
  {
    name: "VSA Prospecting",
    price: "Not publicly stated",
    hasPublicPrice: false,
    model: "Hourly",
    contractTerm: "Not publicly stated",
    channels: ["Phone"],
    qualification: "The buyer supplies a known target market, proven message, and projected appointment-setting process.",
    sourceUrl: "https://vsaprospecting.com/hourly-based-vs-pay-for-perofrmance-appointment-setting-how-to-choose/",
    sourceLabel: "Official pricing-model article",
    lastChecked: LAST_CHECKED,
  },
].sort((a, b) => a.name.localeCompare(b.name));

