export type LibraryKind = "skill" | "playbook" | "tool";
export type LibraryLane = "outbound" | "ai-implementation";
export type LibraryAccess = "public" | "account" | "none";
export type LibraryStatus = "published" | "archived" | "redirected" | "removed";

export interface LibraryItem {
  slug: string;
  title: string;
  summary: string;
  kind: LibraryKind;
  lane: LibraryLane;
  topic: string;
  access: LibraryAccess;
  status: LibraryStatus;
  updatedAt: string;
  source: string;
  relatedAssets: string[];
  commercialTarget: "/appointment-setting" | "/ai-implementation";
  redirectTarget: string | null;
}

const OUTBOUND_TARGET = "/appointment-setting" as const;
const AI_TARGET = "/ai-implementation" as const;

export const LIBRARY_MANIFEST: readonly LibraryItem[] = [
  {
    slug: "cold-offer-review",
    title: "Cold Offer Review",
    summary: "Review an outbound offer before list building or copy begins.",
    kind: "skill",
    lane: "outbound",
    topic: "offer",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/skills/cold-offer-review",
    relatedAssets: ["/skills/buyer-signal-list-research", "/playbooks/outbound-failure-diagnostic"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "buyer-signal-list-research",
    title: "Buyer Signal List Research",
    summary: "Build a source-backed account list around buyer fit and timing signals.",
    kind: "skill",
    lane: "outbound",
    topic: "targeting",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/skills/buyer-signal-list-research",
    relatedAssets: ["/skills/cold-offer-review", "/playbooks/google-maps-outbound"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "outbound-funnel-economics",
    title: "Outbound Funnel Economics",
    summary: "Audit a fixed outbound cohort without replacing unknowns with benchmarks.",
    kind: "skill",
    lane: "outbound",
    topic: "economics",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/skills/outbound-funnel-economics",
    relatedAssets: ["/tools/outbound-funnel-economics-calculator", "/playbooks/outbound-failure-diagnostic"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "list-builder",
    title: "List Builder",
    summary: "Build qualified company and contact lists through explicit research lanes.",
    kind: "skill",
    lane: "outbound",
    topic: "list-building",
    access: "account",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/public-skills/list-builder",
    relatedAssets: ["/skills/list-expander", "/skills/list-quality-scorecard"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "list-expander",
    title: "List Expander",
    summary: "Expand a narrow seed list into a larger set of similar companies.",
    kind: "skill",
    lane: "outbound",
    topic: "list-building",
    access: "account",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/public-skills/list-expander",
    relatedAssets: ["/skills/list-builder", "/skills/buyer-signal-list-research"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "google-maps-list-builder",
    title: "Google Maps List Builder",
    summary: "Build a local-business lead list from defined categories and locations.",
    kind: "skill",
    lane: "outbound",
    topic: "local-outbound",
    access: "account",
    status: "published",
    updatedAt: "2026-08-23",
    source: "content/skills/google-maps-list-builder",
    relatedAssets: ["/playbooks/google-maps-outbound", "/skills/list-quality-scorecard"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "list-quality-scorecard",
    title: "List Quality Scorecard",
    summary: "Check duplicates, title coverage, domains, verification, and ICP fit before sending.",
    kind: "skill",
    lane: "outbound",
    topic: "list-quality",
    access: "account",
    status: "published",
    updatedAt: "2026-08-23",
    source: "content/skills/list-quality-scorecard",
    relatedAssets: ["/tools/csv-list-quality-auditor", "/skills/list-builder"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "icp-prompt-builder",
    title: "ICP Prompt Builder",
    summary: "Turn an ICP definition into a consistent company-fit evaluation prompt.",
    kind: "skill",
    lane: "outbound",
    topic: "qualification",
    access: "account",
    status: "published",
    updatedAt: "2026-08-23",
    source: "content/skills/icp-prompt-builder",
    relatedAssets: ["/skills/buyer-signal-list-research", "/tools/outbound-brief-builder"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "audience-content-os",
    title: "Audience Content OS",
    summary: "Run a source-led content workflow across research, drafting, review, and filing.",
    kind: "skill",
    lane: "ai-implementation",
    topic: "content-systems",
    access: "account",
    status: "published",
    updatedAt: "2026-08-23",
    source: "content/skills/audience-content-os",
    relatedAssets: ["/skills/content-clarity-review", "/playbooks/ai-marketing-team-playbook"],
    commercialTarget: AI_TARGET,
    redirectTarget: null,
  },
  {
    slug: "linkedin-content-writer",
    title: "LinkedIn Content Writer",
    summary: "Draft source-faithful LinkedIn content with explicit approval boundaries.",
    kind: "skill",
    lane: "ai-implementation",
    topic: "content-systems",
    access: "account",
    status: "published",
    updatedAt: "2026-08-23",
    source: "content/skills/linkedin-content-writer",
    relatedAssets: ["/skills/audience-content-os", "/skills/content-clarity-review"],
    commercialTarget: AI_TARGET,
    redirectTarget: null,
  },
  {
    slug: "x-content-writer",
    title: "X Content Writer",
    summary: "Route source-backed ideas into the right native X format.",
    kind: "skill",
    lane: "ai-implementation",
    topic: "content-systems",
    access: "account",
    status: "published",
    updatedAt: "2026-08-23",
    source: "content/skills/x-content-writer",
    relatedAssets: ["/skills/audience-content-os", "/skills/content-clarity-review"],
    commercialTarget: AI_TARGET,
    redirectTarget: null,
  },
  {
    slug: "content-clarity-review",
    title: "Content Clarity Review",
    summary: "Review drafted content for clarity without inventing or approving new claims.",
    kind: "skill",
    lane: "ai-implementation",
    topic: "content-quality",
    access: "account",
    status: "published",
    updatedAt: "2026-08-23",
    source: "content/skills/content-clarity-review",
    relatedAssets: ["/skills/audience-content-os", "/skills/lead-magnets"],
    commercialTarget: AI_TARGET,
    redirectTarget: null,
  },
  {
    slug: "lead-magnets",
    title: "Lead Magnets",
    summary: "Design a useful lead magnet around an evidenced problem and a relevant next step.",
    kind: "skill",
    lane: "ai-implementation",
    topic: "content-systems",
    access: "account",
    status: "published",
    updatedAt: "2026-08-23",
    source: "content/skills/lead-magnets",
    relatedAssets: ["/playbooks/outbound-failure-diagnostic", "/skills/content-clarity-review"],
    commercialTarget: AI_TARGET,
    redirectTarget: null,
  },
  {
    slug: "outbound-failure-diagnostic",
    title: "Outbound Failure Diagnostic",
    summary: "Find the first unsupported or failing stage before changing copy, targeting, or volume.",
    kind: "playbook",
    lane: "outbound",
    topic: "diagnosis",
    access: "public",
    status: "published",
    updatedAt: "2026-08-23",
    source: "content/playbooks/outbound-failure-diagnostic.md",
    relatedAssets: ["/skills/cold-offer-review", "/skills/buyer-signal-list-research", "/skills/outbound-funnel-economics", "/tools/outbound-funnel-economics-calculator"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "claude-code-lead-gen-guide",
    title: "Claude Code Lead Generation",
    summary: "Build and operate a code-assisted lead-research workflow.",
    kind: "playbook",
    lane: "outbound",
    topic: "lead-generation",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/playbooks/claude-code-lead-gen-guide.html",
    relatedAssets: ["/skills/list-builder", "/tools/outbound-brief-builder"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "hermes-outbound-gtm-agent",
    title: "Hermes Outbound GTM Agent",
    summary: "Run a structured outbound workflow through an agent with explicit controls.",
    kind: "playbook",
    lane: "outbound",
    topic: "outbound-agents",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/playbooks/hermes-outbound-gtm-agent.html",
    relatedAssets: ["/playbooks/slack-outbound-agent-playbook", "/skills/list-builder"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "chatgpt-work-self-improving-outbound",
    title: "Self-Improving Outbound with ChatGPT Work",
    summary: "Use explicit review loops to improve an outbound operating workflow.",
    kind: "playbook",
    lane: "outbound",
    topic: "outbound-agents",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/playbooks/chatgpt-work-self-improving-outbound.html",
    relatedAssets: ["/playbooks/hermes-outbound-gtm-agent", "/playbooks/loop-design-playbook"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "google-maps-outbound",
    title: "Google Maps Outbound",
    summary: "Plan a local-business outbound motion from maps research to list review.",
    kind: "playbook",
    lane: "outbound",
    topic: "local-outbound",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/playbooks/google-maps-outbound.html",
    relatedAssets: ["/skills/google-maps-list-builder", "/skills/list-quality-scorecard"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "cold-email-claude-code-blueprint",
    title: "Cold Email with Claude Code",
    summary: "Set up a cold-email workflow with code-based research and clear handoffs.",
    kind: "playbook",
    lane: "outbound",
    topic: "cold-email",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/playbooks/cold-email-claude-code-blueprint.html",
    relatedAssets: ["/skills/cold-offer-review", "/playbooks/outbound-failure-diagnostic"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "slack-outbound-agent-playbook",
    title: "Slack Outbound Agent",
    summary: "Coordinate an outbound agent through a Slack-based operating loop.",
    kind: "playbook",
    lane: "outbound",
    topic: "outbound-agents",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/playbooks/slack-outbound-agent-playbook.html",
    relatedAssets: ["/playbooks/hermes-outbound-gtm-agent", "/playbooks/agentic-sdr-setup-guide"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "agentic-sdr-setup-guide",
    title: "Agentic SDR Setup",
    summary: "Set up an outbound agent around a defined offer, list, and review process.",
    kind: "playbook",
    lane: "outbound",
    topic: "outbound-agents",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/downloads/playbooks/agentic-sdr-setup-guide.pdf",
    relatedAssets: ["/playbooks/slack-outbound-agent-playbook", "/tools/outbound-brief-builder"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "local-ai-build-guide",
    title: "Local AI Build Guide",
    summary: "Plan a local AI system around data boundaries, hardware, and operations.",
    kind: "playbook",
    lane: "ai-implementation",
    topic: "local-ai",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/playbooks/local-ai-build-guide.html",
    relatedAssets: ["/playbooks/mudiagent-operator-guide", "/playbooks/ai-data-agent-guide"],
    commercialTarget: AI_TARGET,
    redirectTarget: null,
  },
  {
    slug: "loop-design-playbook",
    title: "Loop Design",
    summary: "Design an agent loop with explicit state, review, and completion boundaries.",
    kind: "playbook",
    lane: "ai-implementation",
    topic: "agent-systems",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/playbooks/loop-design-playbook.html",
    relatedAssets: ["/playbooks/judgment-moat", "/playbooks/ai-data-agent-guide"],
    commercialTarget: AI_TARGET,
    redirectTarget: null,
  },
  {
    slug: "mudiagent-operator-guide",
    title: "MudiAgent Operator Guide",
    summary: "Operate a local knowledge agent with defined data and maintenance controls.",
    kind: "playbook",
    lane: "ai-implementation",
    topic: "local-ai",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/playbooks/mudiagent-operator-guide.html",
    relatedAssets: ["/playbooks/local-ai-build-guide", "/playbooks/ai-data-agent-guide"],
    commercialTarget: AI_TARGET,
    redirectTarget: null,
  },
  {
    slug: "ai-data-agent-guide",
    title: "AI Data Agent Guide",
    summary: "Plan an AI data agent around explicit sources, transformations, and review.",
    kind: "playbook",
    lane: "ai-implementation",
    topic: "data-agents",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/downloads/playbooks/ai-data-agent-guide.pdf",
    relatedAssets: ["/playbooks/loop-design-playbook", "/playbooks/local-ai-build-guide"],
    commercialTarget: AI_TARGET,
    redirectTarget: null,
  },
  {
    slug: "ai-marketing-team-playbook",
    title: "AI Marketing Team",
    summary: "Design a source-led marketing workflow with clear agent roles and approvals.",
    kind: "playbook",
    lane: "ai-implementation",
    topic: "content-systems",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/playbooks/ai-marketing-team-playbook.html",
    relatedAssets: ["/skills/audience-content-os", "/skills/content-clarity-review"],
    commercialTarget: AI_TARGET,
    redirectTarget: null,
  },
  {
    slug: "coding-agent-seo-playbook",
    title: "Coding Agent SEO",
    summary: "Use coding agents to implement a defined technical SEO change safely.",
    kind: "playbook",
    lane: "ai-implementation",
    topic: "seo",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/playbooks/coding-agent-seo-playbook.html",
    relatedAssets: ["/playbooks/geo-playbook", "/playbooks/loop-design-playbook"],
    commercialTarget: AI_TARGET,
    redirectTarget: null,
  },
  {
    slug: "geo-playbook",
    title: "GEO Playbook",
    summary: "Structure useful source-backed content for retrieval and answer engines.",
    kind: "playbook",
    lane: "ai-implementation",
    topic: "geo",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/playbooks/geo-playbook.html",
    relatedAssets: ["/playbooks/coding-agent-seo-playbook", "/playbooks/judgment-moat"],
    commercialTarget: AI_TARGET,
    redirectTarget: null,
  },
  {
    slug: "judgment-moat",
    title: "Judgment Moat",
    summary: "Design agent systems so human judgment remains explicit and reviewable.",
    kind: "playbook",
    lane: "ai-implementation",
    topic: "agent-systems",
    access: "public",
    status: "published",
    updatedAt: "2026-08-21",
    source: "content/playbooks/judgment-moat.html",
    relatedAssets: ["/playbooks/loop-design-playbook", "/playbooks/geo-playbook"],
    commercialTarget: AI_TARGET,
    redirectTarget: null,
  },
  {
    slug: "appointment-setting-quote-calculator",
    title: "Appointment-Setting Quote Calculator",
    summary: "Compare an appointment-setting quote using held and qualified meeting economics.",
    kind: "tool",
    lane: "outbound",
    topic: "buying",
    access: "public",
    status: "published",
    updatedAt: "2026-08-23",
    source: "src/lib/appointment-setting-calculator.ts",
    relatedAssets: ["/playbooks/outbound-failure-diagnostic", "/tools/outbound-funnel-economics-calculator"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "outbound-funnel-economics-calculator",
    title: "Outbound Funnel Economics Calculator",
    summary: "Calculate supported funnel rates and unit economics from a fixed cohort.",
    kind: "tool",
    lane: "outbound",
    topic: "economics",
    access: "public",
    status: "published",
    updatedAt: "2026-08-23",
    source: "src/lib/outbound-funnel-calculator.ts",
    relatedAssets: ["/skills/outbound-funnel-economics", "/playbooks/outbound-failure-diagnostic"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "csv-list-quality-auditor",
    title: "CSV List Quality Auditor",
    summary: "Check a CSV locally for duplicate, title, domain, verification, and ICP issues.",
    kind: "tool",
    lane: "outbound",
    topic: "list-quality",
    access: "public",
    status: "published",
    updatedAt: "2026-08-23",
    source: "src/lib/csv-list-quality.ts",
    relatedAssets: ["/skills/list-quality-scorecard", "/skills/list-builder"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "outbound-brief-builder",
    title: "Outbound Brief Builder",
    summary: "Create portable Markdown and JSON inputs for the outbound skills.",
    kind: "tool",
    lane: "outbound",
    topic: "planning",
    access: "public",
    status: "published",
    updatedAt: "2026-08-23",
    source: "src/lib/outbound-brief.ts",
    relatedAssets: ["/skills/cold-offer-review", "/skills/buyer-signal-list-research", "/skills/icp-prompt-builder"],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
  {
    slug: "openclaw-outbound",
    title: "OpenClaw Outbound",
    summary: "Legacy duplicate of the Google Maps outbound playbook.",
    kind: "playbook",
    lane: "outbound",
    topic: "local-outbound",
    access: "none",
    status: "redirected",
    updatedAt: "2026-08-23",
    source: "content/playbooks/openclaw-outbound.html",
    relatedAssets: [],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: "/playbooks/google-maps-outbound",
  },
  {
    slug: "revenue-leak-calculator",
    title: "Revenue Leak Calculator",
    summary: "Retired calculator from the previous offer structure.",
    kind: "tool",
    lane: "outbound",
    topic: "archived",
    access: "none",
    status: "removed",
    updatedAt: "2026-08-23",
    source: "src/app/tools/revenue-leak-calculator",
    relatedAssets: [],
    commercialTarget: OUTBOUND_TARGET,
    redirectTarget: null,
  },
];

const KIND_SEGMENTS: Record<string, LibraryKind> = {
  skills: "skill",
  playbooks: "playbook",
  tools: "tool",
};

export function getPublishedLibraryItems(kind?: LibraryKind): LibraryItem[] {
  return LIBRARY_MANIFEST.filter(
    (item) => item.status === "published" && (!kind || item.kind === kind),
  );
}

export function getLibraryItem(kind: LibraryKind, slug: string): LibraryItem | null {
  return LIBRARY_MANIFEST.find((item) => item.kind === kind && item.slug === slug) ?? null;
}

export type LibraryPathResolution =
  | { status: "published"; item: LibraryItem }
  | { status: "redirect"; target: string }
  | { status: "gone" }
  | { status: "not-found" };

export function resolveLibraryPath(pathname: string): LibraryPathResolution {
  const cleanPath = pathname.split(/[?#]/, 1)[0].replace(/\/+$/, "") || "/";
  const [, segment, slug, ...rest] = cleanPath.split("/");
  const kind = KIND_SEGMENTS[segment];
  if (!kind || !slug || rest.length > 0) return { status: "not-found" };

  const item = getLibraryItem(kind, decodeURIComponent(slug));
  if (!item) return { status: "not-found" };
  if (item.status === "published") return { status: "published", item };
  if (item.status === "redirected" && item.redirectTarget) {
    return { status: "redirect", target: item.redirectTarget };
  }
  return { status: "gone" };
}
