// Public playbook preview pages. Static data module.
// Each entry powers a crawlable /playbooks/<slug> page that previews real
// info-gain (excerpt, what's-inside) and gates the full asset behind a free
// account at /portal/playbooks/<slug>. Mirrors the case-studies pattern.

export type PlaybookCategory =
  | "outbound"
  | "sales"
  | "marketing"
  | "seo"
  | "agentic-engineering";

export type PlaybookAccent = "primary" | "emerald" | "sky" | "neutral";

export interface PlaybookMetric {
  value: string;
  label: string;
}

export interface Playbook {
  slug: string;
  /** Short display title (card + breadcrumb). */
  title: string;
  metaTitle: string;
  metaDescription: string;
  /** H1 promise. One line, the outcome the reader gets. */
  hook: string;
  whoItsFor: string;
  outcome: string;
  category: PlaybookCategory;
  keywords: string[];
  /** Specific, real bullets of what the full playbook contains. */
  whatsInside: string[];
  /** 150-300 words of real, standalone-valuable content (the info-gain). */
  excerpt: string;
  topMetrics?: PlaybookMetric[];
  /** Source asset type. Drives the CTA label. */
  format: "html" | "pdf";
  /** ISO date. Real last-updated for sitemap + schema. */
  date: string;
}

export const CATEGORY_META: Record<
  PlaybookCategory,
  { label: string; accent: PlaybookAccent }
> = {
  outbound: { label: "Outbound & Lead Gen", accent: "emerald" },
  sales: { label: "Sales & SDR", accent: "emerald" },
  marketing: { label: "Marketing", accent: "primary" },
  seo: { label: "SEO & GEO", accent: "sky" },
  "agentic-engineering": { label: "Agentic Engineering", accent: "primary" },
};

export const PLAYBOOKS: Playbook[] = [
  {
    slug: "google-maps-outbound",
    title: "Google Maps Outbound Playbook",
    metaTitle: "Google Maps Outbound Playbook: Scrape Local Leads | Muditek",
    metaDescription: "Use Claude Code on a $10/mo server to scrape, enrich, and sequence local business leads from Google Maps that nobody else is emailing.",
    hook: "Turn Google Maps' 265 million business listings into a daily pipeline of enriched local leads using one Claude Code prompt and a $10/mo server.",
    whoItsFor: "B2B founders and agency operators who already have a sharp ICP and offer, and want a self-running outbound engine instead of another headcount.",
    outcome: "A scraping and sequencing machine that drops 500 to 2,000 enriched, never-touched local leads into your pipeline every morning, run by you alone.",
    category: "outbound",
    keywords: ["google maps lead scraping","scrape local business leads","claude code outbound automation","cold email local businesses","google maps outbound playbook","vps cold email infrastructure","enrich leads from google maps","signal based cold email personalization"],
    whatsInside: [
      "The exact Claude Code prompt that builds a Python Google Maps scraper end to end and tells you which RapidAPI endpoints to use",
      "The two-API stack: Business Data Finder (Maps listings) plus Website Contacts Finder (owner email extraction)",
      "Four public Google Maps signals (no website, low reviews, no photos, outdated site) with the verbatim outreach line for each",
      "The 7-step VPS setup: Hostinger or Hetzner, Claude Code plus tmux, Tailscale VPN, Instantly or Smartlead, Telegram alerts, 6am cron",
      "The three-channel stack: email volume engine (35 domains, 105 inboxes, 2,000 sends/day), LinkedIn warm layer, X intent scanner",
      "Honest economics: 2-6% reply rate, 20-40 qualified calls/month, 25% close rate, and where the numbers break",
      "The Monday-to-month-four setup timeline",
      "The build-this-if vs do-not-build-this-if qualification checklist",
    ],
    excerpt: "Most B2B teams pull leads from Apollo, ZoomInfo, and LinkedIn Sales Nav. Same leads, same inboxes, same pile of identical pitches. Google Maps has 265 million business listings: local businesses with outdated websites, 11 Google reviews, and no photos on their profile. Real owners with real pain you can see before writing a single word. And barely anyone is cold emailing them.\n\nThe signal is the personalization. No website becomes \"Couldn't find a website on your Google profile, so I built you a free demo.\" Low reviews becomes \"You have 11 reviews, most competitors in your area have 50+.\" No photos ties to a real outcome: \"businesses with photos get 42% more direction requests.\" These signals are public and verifiable, so outreach feels relevant instead of random.\n\nYou build the pipeline with one Claude Code prompt: \"Build a Python scraper that hits Google Maps for 'dentists in Austin, TX', pulls name, address, phone, website, rating, review count, then crawls each website to extract the owner contact email, outputs to CSV.\" Two RapidAPI endpoints do the work: a Business Data Finder and a Website Contacts Finder.\n\nInfrastructure is a $7-12/mo VPS on Hostinger or Hetzner, Claude Code plus tmux for persistent sessions, Tailscale for access, and a 6am cron job. You wake up to 500 to 2,000 fresh enriched leads. Email runs volume (35 domains, 105 inboxes, 2,000 sends/day with follow-ups at 3, 5, 8, and 14 days), LinkedIn builds familiarity, X catches intent. Honest caveat: these are top-of-range numbers, deliverability is the hardest part, and this targets SMB and local, not enterprise.",
    topMetrics: [
      { value: "265M", label: "Google Maps listings" },
      { value: "$10/mo", label: "VPS scraping cost" },
      { value: "2,000", label: "Enriched leads per day" },
      { value: "2-6%", label: "Reply rate on hyper-local outreach" },
    ],
    format: "html",
    date: "2026-05-11",
  },
  {
    slug: "cold-email-claude-code-blueprint",
    title: "Cold Email at $0.03 a Lead",
    metaTitle: "Cold Email at $0.03 a Lead: Claude Code Stack | Muditek",
    metaDescription: "The exact Claude Code stack, client folder, and three skills that ship a live cold email campaign for the price of the data. About 20 minutes, about $60.",
    hook: "Ship a live cold email campaign end to end for $0.03 a verified lead, with your only job being a two-minute audit.",
    whoItsFor: "Founders and GTM operators who run outbound and want a coding agent to do the list-building, copy, and campaign assembly instead of an agency retainer.",
    outcome: "A campaign that used to take two days of skilled labor now goes from one voice prompt to live in about 20 minutes, with no added headcount.",
    category: "outbound",
    keywords: ["cold email automation with claude code","ai cold email agent","cold email cost per lead","leadmagic verified email enrichment","automate cold email campaign","claude code gtm stack","ai outbound campaign assembly","cold email agency alternative"],
    whatsInside: [
      "The six-piece stack: Claude Code in Antigravity, Wispr Flow voice input, LeadMagic enrichment, Instantly/Lemlist/Smartlead sending, the client folder, and your judgment",
      "The identical six-folder client structure (List Building, ICP Context, Context, Call Recordings, Onboarding Notes, Campaign Briefs) that lets you reuse skills across every account",
      "Why the ABM list sits at 10K to 50K domains and what breaks below and above that band",
      "The three skills that run it: Copywriting (60-80 words, give-first, no calendar ask), List Building, and Campaign Assembly",
      "The operator preamble every skill opens with, plus the single under-90-second prompt that oneshots a campaign",
      "The exact 20-minute run: 105 verified, minus 50 deduped, minus 9 blocked, 28 live with an A/B test",
      "The two-minute audit and the same four misses every time: subject lines, CTA, sequence at day 4/9/16, and variable spot-check",
      "The self-improving loop that reads reply data daily and cross-client compounding across 400+ companies",
    ],
    excerpt: "Three years ago this campaign was two full days of skilled work. Map the TAM, pull personas, scrape titles, enrich domains, verify, scrub the block list, write fresh copy, upload, configure the sequence, QA every variable. That is what the retainer paid for. It now costs the price of the data and a coffee's worth of review time.\n\nThe shift in one line: you stop paying for the execution. The only hard cost left is the data. Per verified email is $0.03. A 2,000-credit cap holds the data cost near $60 a run. Your time in the loop is about two minutes, the audit.\n\nWhen a client signs, the first thing you build is the agent's folder, identical for every account: List Building, ICP Context, Context, Call Recordings, Onboarding Notes, Campaign Briefs. The model isn't smart. The folder is.\n\nThree skills do the heavy lifting. Copywriting enforces 60 to 80 words, opens give-first never with credentials, no meeting ask in the first message, mirrors the prospect's language. List Building queries the API, dedupes against live campaigns, verifies, scrubs the block list. Campaign Assembly creates the campaign, uploads leads, configures the sequence, sets up the subject-line A/B test.\n\nOne spoken prompt runs it: open the client folder, take the ICP titles, cross-reference the ABM list, use the LeadMagic API for verified emails, cap credits at 2,000, draft the copy, build the campaign, oneshot it. The run returns 105 verified prospects, drops 50 dupes and 9 blocked, lands at 28 live. The audit is ceremonial. The real work happened in the twenty minutes before.",
    topMetrics: [
      { value: "$0.03", label: "per verified email" },
      { value: "~$60", label: "data cost per run, 2,000-credit cap" },
      { value: "~20 min", label: "one prompt to live campaign" },
      { value: "28", label: "verified prospects out, campaign live" },
    ],
    format: "html",
    date: "2026-05-30",
  },
  {
    slug: "ai-marketing-team-playbook",
    title: "Build an AI Marketing Team That Stops Producing Slop",
    metaTitle: "AI Marketing Team: 5-Gate Anti-Slop System | Muditek",
    metaDescription: "The five-gate system, role-card prompts, and draft-vs-critique protocol to run a marketing team of AI agents that argue before they publish.",
    hook: "Run a marketing team of AI agents that argue before they publish, so your AI stops shipping the beige paragraph everyone else does.",
    whoItsFor: "For operators and founders who want AI to produce real marketing work, not a confident yes-man that agrees with every brief.",
    outcome: "An agent team that drafts, attacks its own work, and hands you a reviewable decision memo, with no added marketing headcount.",
    category: "agentic-engineering",
    keywords: ["ai marketing team","ai agents marketing","multi-agent prompt system","stop ai slop","role card prompt schema","ai content review workflow","adversarial ai agents","decision memo ai content"],
    whatsInside: [
      "The five-gate checklist (Intake, Specialist, Adversary, Lead, Memo) and the exact slop each gate stops if you delete it",
      "The Marketing Intake Gate: the five questions the Lead must get answered (objective, audience, channel, proof, constraint) before any drafting starts",
      "The Role Card Schema: Job / Input / Output / Forbidden / Stop, plus filled Writer and Skeptic cards built to disagree",
      "The persona-prompt vs filter-prompt table showing why 'you are an expert copywriter' produces a cosplay bot",
      "The Draft vs Critique Protocol: a fixed three-round fight that ends in checkable claims, not 'I like it / I don't'",
      "The Content Decision Memo template: core promise, case for, case against, key assumptions, kill condition, risks, next action, confidence",
      "The Four Seats (Researcher, Writer, Skeptic, Editor) and how the same system maps onto demand gen, product marketing, and sales",
      "The honest limits: garbage proof in, garbage memo out, and why the Writer and Skeptic must be two real agents not one prompt",
    ],
    excerpt: "A single AI agrees with you too much. Ask if your draft is good, it tells you it is great. Ask for a hook, it hands you the safe one. A bigger model does not fix this. The fix is an org chart, not a smarter model.\n\nA usable team comes down to five gates. Miss one and the whole thing leaks. Without Intake, the team perfectly executes the wrong brief. Without Specialist, every role blurs into the same mush. Without Adversary, the team hypes your draft and ships slop. Without Lead, you get a pile of disconnected fragments. Without Memo, you make the same mistake next campaign.\n\nGate 1 is the Marketing Intake Gate. Before drafting starts, the Lead must get five things clear: Objective (pipeline, signups, awareness, retention), Audience (role, stage of awareness, the pain in their words), Channel, Proof (real evidence and numbers, plus what you are NOT allowed to claim), and Constraint (brand rules, banned words, legal lines, length). Give it \"we need something for the launch\" and it should come back with questions, not copy. The refusal is the feature.\n\nRoles are filters, not personas. A weak prompt says \"you are an expert copywriter, make this engaging.\" A strong one says: \"one promise, one reader. Tag every claim to a real source. Refuse if there is no claim to make.\" The Writer wants to ship. The Skeptic wants to cut. Their jobs point in opposite directions by design, so you never fake the tension. The output is not \"publish this,\" it is a decision memo: core promise, case for, case against, key assumptions, kill condition, next action.",
    format: "html",
    date: "2026-06-04",
  },
  {
    slug: "agentic-sdr-setup-guide",
    title: "Agentic SDR Setup Guide",
    metaTitle: "Agentic SDR Setup Guide: 3-Channel Outbound | Muditek",
    metaDescription: "Run X, cold email, and LinkedIn as one coordinated agentic SDR system. The sequence, stack, data model, and rollout logic. No large human SDR team.",
    hook: "Run X, cold email, and LinkedIn as one coordinated outbound machine without first hiring a large human SDR team.",
    whoItsFor: "Founders and operators who already have a clear offer and sharp ICP and want repeatable outbound run by AI agents, not more headcount.",
    outcome: "A documented multi-channel SDR system where agents read signals, send the right touch, log it, and escalate exceptions, so outbound economics behave like software instead of headcount.",
    category: "outbound",
    keywords: ["agentic sdr setup","ai sdr system","multi-channel outbound sequence","cold email linkedin x outbound","ai outbound automation stack","automated outbound without headcount","outbound orchestration system","ai sdr playbook"],
    whatsInside: [
      "The 3-channel rhythm: X DM on day 1, cold email day 3, LinkedIn day 5, progressive follow-ups day 7 to 14, run as one sequence with one memory",
      "Channel jobs: X for attention arbitrage, email for the real offer, LinkedIn as the identity layer, follow-up for compounding value, each kept in character",
      "The lean stack: Hostinger VPS, Tailscale, OpenClaw orchestration, Telegram command bot, Instantly, PhantomBuster, Drippi, Apollo, and one shared database",
      "The data-first system of record: who the prospect is, why selected, what signal triggered outreach, which angle is active, which channel touched, what happened next",
      "The minimum documentation stack: ICP and exclusions, signal-to-problem map, channel rules, offer library, escalation rules, logging rules",
      "Six message rules plus the bad-automation list to avoid (fake personalization, compliment openers, just-checking-in follow-ups)",
      "The 6-step rollout: Strategy, Infrastructure, Message System, Hardening, Controlled Launch, Optimization, over 6 to 8 weeks",
      "The build-this-if vs do-not-build-this-if qualification checklist before you automate anything",
    ],
    excerpt: "The bottleneck in outbound is rarely effort. It is coordination. Traditional outbound breaks when volume rises: follow-ups get skipped when calendars fill, messaging drifts the moment reps improvise, logging gets messy so the team stops learning, and channels run as separate campaigns instead of one system. The fix is to turn three channels into one sequence with one memory. Day 1 an X DM creates early relevance, light and intentionally low pressure. Day 3 cold email carries the clearest commercial message: name the problem, point to a believable mechanism, make a small low-friction offer, not a forced meeting. Day 5 LinkedIn adds identity and context, peer-to-peer. Day 7 to 14 follow-ups add something new each time: sharper diagnosis, clearer mechanism, example, framework, or proof, never just repeating the ask. Do not paste the same message everywhere. Each channel gets a different job and stays in character. Small offers that work: short teardown, problem breakdown, setup guide, decision framework, compact diagnostic. The database comes before the message. An agent without documentation is just automated randomness. You need one clean system of record and a judgment layer: ICP and exclusions, a signal-to-problem map, channel rules, an offer library, escalation rules, and logging rules. The real job of AI here is narrow: read the signal, map it to a likely problem, select the right message pattern, send or queue the touch, log what happened, escalate exceptions. The model is not your GTM brain. The lean core stack runs around $269 a month, but the moat is the architecture: one environment, one orchestrator, one command surface, one clean data layer. If the offer or list is weak, the same stack will simply scale irrelevance faster.",
    topMetrics: [
      { value: "$269", label: "approximate lean core stack per month" },
      { value: "157", label: "conservative modeled calls per month" },
      { value: "4,140", label: "modeled daily touches across channels" },
      { value: "6-8 weeks", label: "for a proper rollout" },
    ],
    format: "pdf",
    date: "2026-05-11",
  },
  {
    slug: "coding-agent-seo-playbook",
    title: "Coding Agents Can Run Your SEO",
    metaTitle: "Run SEO With Coding Agents: 17 Recipes | Muditek",
    metaDescription: "17 paste-ready prompts that turn Claude Code or Codex into a full SEO team. Live SERP data, evidence-based edits, audit trail. No SEO background needed.",
    hook: "Paste 17 production-grade prompts into Claude Code or Codex and run a full enterprise SEO team out of one terminal.",
    whoItsFor: "Founders, operators, agencies, and in-house SEO teams who are tired of generic AI prompts and want real, evidence-based SEO work run by an agent across 1 page or 20,000.",
    outcome: "Recover stuck pages, build site-wide internal links, refresh stale content, and ship client-ready audit PDFs without hiring a junior SEO, a writer, a developer, or a PM.",
    category: "seo",
    keywords: ["run SEO with Claude Code","coding agent SEO automation","Codex SEO prompts","AI SEO recipes for agents","on-page SEO MCP setup","automate internal linking AI agent","recover stuck page SEO prompt","evidence-based AI SEO workflow"],
    whatsInside: [
      "Recipe 1: Recover a stuck page in one command, targeting 34 Google ranking factors across six families with a scan, fix, rescan loop",
      "Recipe 2: Site-wide internal links from 50 to 20,000+ pages using a resumable JSON manifest, 75-page runs, 10-page batches, max 3 links per page",
      "The three-layer model: live SERP data (on-page-seo MCP) + 17 years of interpretation heuristics + the recipes themselves",
      "The two non-negotiable rules: preserve human writing (the racterScores AGC signal) and justify every change with a specific scan signal",
      "Five-minute setup: connect the on-page-seo MCP, plus WordPress REST (Application Passwords) or SSH, easy vs safer .env method",
      "Recipes 9 and 10: full client website audit and single-page audit as polished PDFs with a 30/60/90 plan",
      "Recipe 11: diagnose-only 'why isn't this page ranking' returning the top 1 to 3 likely causes with no edits",
      "Recipes 14-17: local SEO suite covering NAP, GBP alignment, LocalBusiness schema, and a cross-region cannibalization checker",
    ],
    excerpt: "Most \"AI SEO automation\" fails for one reason: the model gets a URL, a keyword, and \"optimize this page,\" so it parrots back the same advice every consultant has sold for ten years. It has no idea what's ranking right now, what entities competitors cover, or which of 200+ ranking factors your page is missing. The fix is not a smarter prompt. It is feeding the agent the same intelligence a senior SEO wants before touching a page: live SERP data, competitor benchmarks, entity gaps, Highly Related Words, category signals, internal link opportunities, and algorithmic scores, then telling it exactly what to do, step by step, with verification.\n\nThis playbook is built on a three-layer model. Layer 1 is real-time data through the on-page-seo MCP. Layer 2 is interpretation context (17+ years of SEO heuristics) bundled inside the MCP so the agent knows which gaps matter and which are noise. Layer 3 is the 17 recipes.\n\nTwo rules are non-negotiable. Rule 1: preserve human writing. The Google algorithm leak surfaced racterScores, a value monitoring Artificially Generated Content, so the target is doing the SEO work around the human writing, not on top of it. Rule 2: justify each change with evidence. Every edit ties to a specific signal in the scan report (missing entity, weak alt-text, thin content versus competitors). Every recipe ends with an HTML report showing before/after scores, which entities were added, which were skipped and why. Recipe 1 alone targets 34 ranking factors and in one real run worked for nearly 25 minutes, updating the page multiple times.",
    format: "html",
    date: "2026-05-26",
  },
  {
    slug: "clawchief-blueprint",
    title: "The Chief of Staff Blueprint",
    metaTitle: "Chief of Staff Blueprint: Replace a $75K EA | Muditek",
    metaDescription: "Turn an AI agent into an autonomous chief of staff with 8 markdown files, 4 skills, and 3 cron jobs. Inbox, calendar, outreach, tasks. Verbatim build.",
    hook: "Replace a $75K executive assistant with 8 markdown files, 4 skills, and 3 cron jobs that run your inbox, calendar, and outreach while you sleep.",
    whoItsFor: "Founders and operators who already run an AI agent and want it to act like a proactive chief of staff, not a passive chatbot.",
    outcome: "The boring 80% of an EA's day becomes files and crons, with no added headcount, while judgment and relationships stay yours.",
    category: "agentic-engineering",
    keywords: ["replace executive assistant with AI agent","AI chief of staff setup","autonomous AI agent inbox calendar","OpenClaw chief of staff blueprint","cron job AI assistant automation","AI agent priority map auto-resolver","agentic operating system markdown files"],
    whatsInside: [
      "The 3-layer rule: skills define how to act, files define who to act for, crons define when to wake up",
      "priority-map.md person and program block templates with P0 to P3 urgency and four action modes",
      "auto-resolver.md and its five-condition safe-auto-resolve checklist for acting alone vs drafting vs escalating",
      "HEARTBEAT.md, the exact 11-step sequence the agent runs every 15 minutes",
      "tasks.md structure plus the 9 non-negotiable task-file rules and overnight archive to tasks-completed.md",
      "meeting-notes.md 7-step ingestion workflow that turns calls into tasks with a JSON ledger",
      "All 4 skills (executive-assistant, business-development, daily-task-manager, daily-task-prep) with gog queries and reply templates",
      "The 3 cron job configs, 13 install values, 7-step install flow, and full validation checklist",
    ],
    excerpt: "Most AI assistants are passive. A chief of staff wakes up. It checks your inbox at 8:15am, your calendar at 8:30, your CRM at 9, and only interrupts you when something actually needs you. This blueprint defines the missing operating system in three portable layers. Skills tell the agent how to act. Files tell it who to act for. Crons tell it when to wake up. Without all three you have a chatbot. With all three you have an operator.\n\nPrioritization lives in priority-map.md and nowhere else: every signal maps to people, programs, an urgency level (P0 interrupt now, P1 same day, P2 digest, P3 archive), and one of four action modes. Resolution policy lives in auto-resolver.md, which only acts alone when all five conditions are true: the signal is clearly understood, the source of truth is known, the action is operational not strategic, authority is already clear, and a mistake would be low-cost and recoverable. If any fail, it drafts and asks.\n\nHEARTBEAT.md is the 11-step sequence the agent runs every 15 minutes, 8am to 9pm, around 52 sweeps a day. It reads the priority map, the auto-resolver, meeting notes, and the live task file, runs the executive-assistant workflow, auto-resolves low-risk items, and replies HEARTBEAT_OK when there is nothing useful to say. Three cron jobs drive it: the EA sweep, a 2am daily task prep that builds tomorrow's list, and a 2am sourcing job that pulls 10 verified leads into your CRM. Common mistake: enabling all 3 crons before customizing the priority map, which buys you 52 useless sweeps a day.",
    topMetrics: [
      { value: "$75K/yr", label: "EA salary the stack replaces" },
      { value: "8 / 4 / 3", label: "markdown files, skills, cron jobs" },
      { value: "~45 min", label: "clone to first heartbeat" },
      { value: "52", label: "inbox sweeps per day, 8am to 9pm" },
    ],
    format: "html",
    date: "2026-05-11",
  },
  {
    slug: "geo-playbook",
    title: "Cited, Not Ranked: The GEO Playbook",
    metaTitle: "GEO Playbook: Get Cited by AI Search | Muditek",
    metaDescription: "The complete GEO playbook to make ChatGPT, Perplexity, Claude and Google AI Overviews find, read, and cite your content. Base setup takes one hour.",
    hook: "Make ChatGPT, Perplexity, Claude and Google AI Overviews cite your content, with a base setup that takes about one hour.",
    whoItsFor: "Operators and founders who want their brand named and cited inside AI answers, not buried on page two of Google.",
    outcome: "Your pages get found, read, and cited accurately by AI engines without adding headcount or a week of SEO work.",
    category: "seo",
    keywords: ["generative engine optimization playbook","how to get cited by chatgpt","llms.txt setup guide","optimize for ai overviews","get cited by perplexity","geo vs seo","ai search optimization for brands","indexnow bing ai search"],
    whatsInside: [
      "Step 1: sort the five AI crawler types in robots.txt (training, search and retrieval, user-triggered, opt-out tokens, undeclared) so you do not vanish from AI search",
      "Step 2: write an llms.txt site summary, with a copy-paste format and a filled-in Acme Analytics example, plus where to submit it",
      "Step 4: serve llms-full.txt and .md routes that cut a 15,000-token HTML page to ~3,000 tokens of pure content",
      "Steps 5-6: register with Google Search Console and Bing, turn on IndexNow with the exact key file and POST payload to ping changed URLs",
      "Step 9: the per-project page template (citable summary, comparison, use cases, install commands) that actually earns citations",
      "Part 4: the nine tested content changes ranked by lift, Cite Sources, Quotation, Statistics each +30-40%, Keyword Stuffing 10% worse than nothing",
      "Part 5: the tactics that waste time, ai.txt, HTML comment hints, user-agent cloaking, FAQ-stuffing, and the JSON-LD reality",
      "Part 6: the honest limits, llms.txt has no proven citation lift yet, and AI attribution is wrong 60%+ of the time",
    ],
    excerpt: "The page ChatGPT cites and the page Google ranks are usually two different pages. Only 6.82% of the pages ChatGPT cites also sit in Google's top 10, and nearly a third of the most-cited AI pages do not rank on Google at all. 83% of AI Overview citations come from pages outside the organic top 10. On queries that surface an AI answer, organic clicks fall about 61%, but brands cited inside that answer pick up a +35% click lift while everyone else bleeds out.\n\nGEO is a brand-visibility play, not a traffic play. It is worth one hour of setup, not a week. The base is five moves: sort AI crawlers in robots.txt (block training, allow search and retrieval, or the site vanishes from AI search), publish an llms.txt summary at the root, serve llms-full.txt plus .md routes that strip a 15,000-token HTML page down to about 3,000 tokens, register with Google Search Console and Bing, and turn on IndexNow so Bing is notified the moment you publish. Bing matters more than its market share: Copilot, DuckDuckGo, Yahoo and ChatGPT search all run on the Bing index underneath.\n\nWhat actually moves citation, from controlled testing across a 10,000-query benchmark: Cite Sources, Quotation Addition, and Statistics Addition each lift visibility 30 to 40%. Keyword stuffing scores about 10% worse than doing nothing. Front-load value, 44.2% of citations come from the first 30% of the text. Pure FAQ format actively hurts, the opposite of what most GEO-score tools advise.",
    topMetrics: [
      { value: "6.82%", label: "of ChatGPT-cited pages also rank in Google's top 10" },
      { value: "83%", label: "of AI Overview citations come from outside the organic top 10" },
      { value: "+115%", label: "visibility lift from Cite Sources on a page ranked #5" },
      { value: "~1 hour", label: "base setup time for the first five steps" },
    ],
    format: "html",
    date: "2026-06-01",
  },
  {
    slug: "claude-code-tips",
    title: "Claude Code Power User Playbook",
    metaTitle: "Claude Code Power User Playbook: 45 Tips | Muditek",
    metaDescription: "45 Claude Code tips from someone who runs a whole business through it. Voice input, git worktrees, handoff docs, parallel subagents, and more.",
    hook: "Run your whole operation through Claude Code: voice input, parallel agents, and clean context handoffs that 10x your output.",
    whoItsFor: "For operators and founders who want to run real work through Claude Code, not just dabble in vibe-coding.",
    outcome: "You get more done per day by delegating tedious digital work to 3 parallel Claude Code agents without hiring anyone.",
    category: "agentic-engineering",
    keywords: ["claude code tips","claude code power user","claude code voice input","git worktrees claude code","claude code subagents parallel","claude code context handoff","run claude code from phone","claude code workflow"],
    whatsInside: [
      "Voice-to-Claude setup (superwhisper, MacWhisper, EarPods) that runs 3-5x faster than typing, even on a plane",
      "The HANDOFF.md pattern: write a handoff doc, review it, start fresh so the next agent loads one file and finishes the task",
      "Git worktrees recipe to run 3 independent Claude Code agents shipping features simultaneously from one repo",
      "Background subagents with Ctrl+B plus model selection (Opus/Sonnet/Haiku) for parallel codebase analysis",
      "Slim the system prompt from ~19k to ~9k tokens, plus lazy-load MCP tools with ENABLE_TOOL_SEARCH",
      "The tmux write-test cycle that lets Claude run git bisect and fix CI autonomously",
      "cc-safe command audit to catch risky approved commands like rm -rf before they wipe your home directory",
      "The self-check verification prompt: double-check every claim and produce a table of what was verified",
    ],
    excerpt: "Most people use Claude Code at 10% of its power. A few recipes from the playbook that stand alone:\n\nVoice beats typing. Using a local transcription model (superwhisper, MacWhisper, or open-source Super Voice Assistant), you communicate 3-5x faster. Even when words get mistranscribed, Claude infers intent. The author whispers into Apple EarPods in offices and on planes and runs his entire business this way.\n\nContext is like milk, best served fresh and condensed. Start a new session for every new topic. Before clearing, ask Claude to write a HANDOFF.md explaining what was tried, what worked, what did not, so the next fresh agent loads only that file and finishes the task. Review it, then start clean.\n\nRun agents in parallel. A git worktree is a branch plus its own directory: git worktree add ../my-project-feature-1 feature-1, then cd in and launch Claude. Three worktrees equal three agents shipping features at once. Press Ctrl+B to push a command to the background, and spawn background subagents on Opus, Sonnet, or Haiku for different parts of a large codebase.\n\nCut the overhead. Claude Code's system prompt and tool definitions eat about 19k tokens (~10% of 200k) before you start. Patching trims that to ~9k. Add ENABLE_TOOL_SEARCH to lazy-load MCP tools only when needed.\n\nVerify everything. A favorite prompt: \"double check everything, every single claim in what you produced, and at the end make a table of what you were able to verify.\" And run cc-safe to scan approved commands for danger like rm -rf or sudo.",
    topMetrics: [
      { value: "45", label: "tips, Tip 0 through Tip 45" },
      { value: "~10k", label: "tokens saved by slimming the system prompt (~50%)" },
      { value: "3", label: "parallel agents via git worktrees" },
      { value: "200k", label: "context window on Opus 4.5" },
    ],
    format: "html",
    date: "2026-05-11",
  },
  {
    slug: "skill-creator-blueprint",
    title: "The Skill Creator Blueprint",
    metaTitle: "How to Build Claude Skills That Work | Muditek",
    metaDescription: "Build reusable Claude Skills that remember your business rules. The 3-layer architecture, SKILL.md rules, and skill-creator auto-build loop, explained.",
    hook: "Teach Claude your process once in a single file, and every person on your team gets the same expert output forever.",
    whoItsFor: "Operators and founders who use Claude daily and are tired of re-explaining the same rules, formats, and workflows every session.",
    outcome: "A repeatable system that turns your unwritten work process into explicit AI Skills, so output stays consistent across your whole team with no added headcount.",
    category: "agentic-engineering",
    keywords: ["how to build claude skills","claude skill.md format","skill-creator claude code","3-layer skill architecture","mcp vs skills","progressive disclosure claude skills","when to create a claude skill","agent skills marketplace"],
    whatsInside: [
      "The 3-layer architecture (Header, Instructions, Reference Files) and how progressive disclosure lets you stack 50+ Skills with zero slowdown",
      "The two non-negotiable rules for writing SKILL.md: only write what Claude doesn't already know, and keep it under 500 lines",
      "The 5-step skill-creator auto-build loop: Ask, Generate, Test, Evaluate, Repeat, with the real app-launch prompt example",
      "How to match instruction 'degrees of freedom' to the task: High, Moderate, and Low freedom patterns",
      "MCP vs Skills explained with the kitchen-vs-recipe model, and why most people have a kitchen full of tools and zero recipes",
      "The decision test for when to build a Skill vs just stating it in chat",
      "Real metadata and content-body examples from a working presentation Skill, plus the full folder structure",
      "How to install Skills via the /plugin command and the document-skills and example-skills packs",
    ],
    excerpt: "Skills solve three pains at once: re-giving the same instructions every session, Claude never remembering your rules and formats, and a team where only the good prompters benefit. You teach Claude your process once in a single file, it remembers forever, and everyone gets the same quality.\n\nWhat separates Skills that work from Skills that choke on context is the 3-layer architecture. Layer 1 is the Header: YAML metadata with name and description that Claude reads at startup, costing only a few dozen tokens, so you can install many Skills without filling the context window. Whether a Skill actually fires depends heavily on getting that description right. Layer 2 is Instructions, loaded only when triggered, kept under 500 lines. Layer 3 is Reference Files, loaded on demand. This progressive disclosure feeds information gradually, avoiding a one-time overload.\n\nTwo rules govern the content section. First: \"Default assumption: Claude is already very smart. Only add context Claude doesn't already have.\" Skip general programming basics and library docs. Write company-specific rules, internal tool quirks, and team formatting standards. Second: match the degrees of freedom to the task. High freedom for creative work (text direction, not scripts), low freedom when consistency is crucial and mistakes are fatal (specific scripts, few parameters).\n\nMCP vs Skills is kitchen vs recipe. MCP gives Claude access to tools, your CRM, inbox, database. Skills are the step-by-step recipes for using those tools your way. Most people have a kitchen full of tools and zero recipes. The decision test: if you have explained the same rules, format, or process to Claude more than twice, that is a Skill waiting to be built.",
    topMetrics: [
      { value: "400,856", label: "open-source Skills available" },
      { value: "<500", label: "lines max per SKILL.md" },
      { value: "5 steps", label: "in the skill-creator loop" },
    ],
    format: "html",
    date: "2026-05-11",
  },
  {
    slug: "claude-code-self-evolving",
    title: "Claude Code: Self-Evolving System",
    metaTitle: "Claude Code Self-Evolving System Setup | Muditek",
    metaDescription: "Build a Claude Code setup that captures every correction, turns it into a verified rule, and drops corrections from 4-5 per session to near zero by session 20.",
    hook: "Turn Claude Code into a system that captures every correction and turns it into a permanent rule it never breaks again.",
    whoItsFor: "Operators and founders who run Claude Code on real projects and are tired of re-correcting the same mistakes every session.",
    outcome: "A self-improving Claude Code setup that drops corrections from 4-5 per session to near zero by session 20, with no extra engineers.",
    category: "agentic-engineering",
    keywords: ["claude code self-evolving system","claude code CLAUDE.md setup","claude code memory and rules","claude code subagents architect reviewer","claude code hooks settings.json","claude code learned rules verification","agentic engineering claude code"],
    whatsInside: [
      "The four-layer architecture: cognitive core (CLAUDE.md), specialized subagents, path-scoped rules, and the evolution engine",
      "The exact CLAUDE.md decision framework Claude runs before writing code: grep first, blast radius, ask one question, smallest change, verification plan",
      "settings.json allow/deny permissions plus three automation hooks (SessionStart, PreToolUse, Stop) that make checks structural, not optional",
      "Path-scoped security, API-design, and performance rules that only load when editing matching files to keep context lean",
      "Architect and reviewer subagent definitions with isolated context, scoped tools, and fixed output formats",
      "The evolution engine SKILL.md: verification sweep, hypothesis-driven observations, correction capture, and session scoring",
      "The promotion ladder: corrected once, corrected twice auto-promotes to learned-rules.md, observed 3+ times, graduates to CLAUDE.md after 10+ sessions",
      "A one-command setup script and a 9-point test checklist to prove every layer works",
    ],
    excerpt: "Most learning systems are journals. This one is an immune system. The core idea: a rule without a verification check is a wish. A rule with a verification check is a guardrail. Only guardrails survive. Here is the loop in practice. Session 1: you tell Claude \"we never use ternary operators here, always use if/else.\" The evolution skill logs the correction to corrections.jsonl and generates a verify pattern: Grep(\"? .* : \", path=\"src/\") returns 0 matches. Session 3: Claude writes a ternary again, you correct it, and because it is the second time on the same pattern it auto-promotes to learned-rules.md with the verification check attached. Session 5: before writing anything, a silent verification sweep runs every verify line in learned-rules.md. By session 20 the system has 8 learned rules with checks, 3 graduated to permanent config, 2 pruned, and corrections are near zero. The promotion ladder is explicit: corrected once goes to corrections.jsonl, corrected twice goes to learned-rules.md, observed 3+ times goes to learned-rules.md, and anything in learned-rules for 10+ sessions graduates to CLAUDE.md or rules/. Observations are never guesses. You formulate a testable claim, grep for counter-examples immediately, and only log it with evidence. learned-rules.md is capped at 50 lines, which forces graduation or pruning. CLAUDE.md stays under 150 lines or instruction adherence drops. Three SessionStart, PreToolUse, and Stop hooks make the checks structural so no step depends on Claude remembering to run it.",
    topMetrics: [
      { value: "4-5 → 0", label: "corrections per session" },
      { value: "20", label: "sessions to full evolution" },
      { value: "50", label: "line cap on learned-rules.md" },
      { value: "<150", label: "lines max for CLAUDE.md" },
    ],
    format: "html",
    date: "2026-05-11",
  },
  {
    slug: "slack-outbound-agent-playbook",
    title: "Run Outbound From One Slack Channel",
    metaTitle: "Run Outbound From One Slack Channel | Muditek",
    metaDescription: "Replace ten outbound tools with one Slack agent. Install path, 5-file memory vault, DNS MX gate, and the recipe that pulled 45 verified leads from free data.",
    hook: "Run your entire outbound from one Slack channel with a persistent-memory agent that picks the verticals, scrapes the data, validates the emails, and launches campaigns while you sleep.",
    whoItsFor: "Founders and operators running outbound themselves, agencies pivoting from \"we run your outbound\" to agents-as-a-service, and in-house GTM teams that want overnight throughput without hiring three more SDRs.",
    outcome: "One open-source agent replaces ten outbound subscriptions and the eight hours a week a human spends stitching them together, with no added headcount.",
    category: "outbound",
    keywords: ["slack outbound agent","persistent memory agent","free data lead generation","DNS MX check prospecting","cold email automation","openclaw harness","agents as a service","cli first agent tooling"],
    whatsInside: [
      "The three terminal commands to install the harness and wire it to Slack via Socket Mode",
      "The 5-file memory vault at ~/.openclaw/workspace/memory/ plus Memory Protocol, Retrieval Protocol, and a pre-compaction flush",
      "The DNS MX check rule: pull domain, run MX lookup, drop rows with no MX record before spending any enrichment credit",
      "The free-data recipe that produced 45 verified leads from $0: vertical ranking, G2/Capterra pain mining, public directory volume, overnight async run",
      "Campaign launch parameters: 3-step cadence at day 1/4/9, 10 emails per inbox times 10 secondary domains equals 100/day from cold start",
      "The self-correction loop where every mistake (API casing, spam-trap rows) becomes a permanent rule in memory/lessons.md",
      "The fleet pattern: outbound, marketing, sales-intel, and content agents on one harness with different system prompts",
      "The 12-step hardening checklist and the 7-day install path, day by day",
    ],
    excerpt: "The friction in outbound is not the tools. It is that a human is the integration layer between platforms that do not talk to each other, spending roughly eight hours a week stitching outputs together by hand. This playbook collapses that stack into one Slack channel and one open-source agent with persistent memory on disk. The reference live build produced 45 verified leads from $0 of paid enrichment, using only public data, in four Slack messages, in roughly one hour. The install is three terminal commands (npm install -g openclaw@latest, openclaw onboard --install-daemon, openclaw gateway status) plus a Socket Mode wizard. Then you seed a 5-file memory vault: MEMORY.md as the index, projects.md for the ICP and offers, infra.md for the tool stack, lessons.md for corrections, and a dated daily log. Two non-negotiable additions sit on top: a Memory Protocol and a Retrieval Protocol. The single rule worth memorizing is the DNS MX check: pull the company domain, run an MX lookup, and if there is no MX record the domain cannot receive email so drop the row, before any enrichment credit is spent. It runs in milliseconds and is the difference between a usable list and a junk list. Pain gets mined from G2 and Capterra in the buyer's own words, and each complaint becomes an outbound trigger lifted verbatim into the sequence. Campaigns launch from inside Slack at a 3-step cadence on day 1, 4, and 9, with 10 emails per inbox across 10 secondary domains for 100 per day from cold start. Every mistake the agent makes once becomes a rule in memory/lessons.md, so each batch starts ahead of the last.",
    topMetrics: [
      { value: "45", label: "verified leads from $0 paid enrichment" },
      { value: "3 cmds", label: "to install and wire to Slack" },
      { value: "5 files", label: "persistent memory vault" },
      { value: "100/day", label: "emails from cold start" },
    ],
    format: "html",
    date: "2026-05-28",
  },
  {
    slug: "gtm-skills-guide",
    title: "GTM Skills Library Guide",
    metaTitle: "GTM Skills Library Guide: 103 AI Skills | Muditek",
    metaDescription: "103 open-source GTM skills for Claude Code that run lead gen, outreach, competitor intel, SEO and ads as autonomous workflows. Install once, use forever.",
    hook: "Install 103 open-source AI skills that run your lead gen, outreach, competitor intel, SEO and ads as autonomous workflows.",
    whoItsFor: "Operators and founders who run go-to-market themselves and want AI agents to do the actual prospecting, research, and outreach work instead of prompting for advice.",
    outcome: "Your AI agent runs full GTM workflows end to end, from finding leads to drafting outreach, with no added headcount.",
    category: "marketing",
    keywords: ["GTM skills","Claude Code skills","AI agents GTM","lead generation automation","competitor intelligence","outreach automation","AI SDR","agentic engineering"],
    whatsInside: [
      "How a skill works: each is a folder with two files, SKILL.md (step-by-step instructions) and skill.meta.json (registry metadata)",
      "Install in 3 steps: npx goose-skills install competitor-intel, copy SKILL.md into .claude/skills/, then describe the task to Claude",
      "Find leads: apollo-lead-finder runs two-phase Apollo prospecting and dedupes against Supabase, plus icp-identification, tam-builder, competitor-post-engagers, pain-language-engagers",
      "Automate outreach: cold-email-outreach selects leads, writes a 3-5 email sequence, and pushes to Smartlead or Instantly, plus funding, hiring, and champion-move signal-triggered outreach",
      "Competitor intel: competitor-intel, battlecard-generator, competitive-pricing-intel with Wayback history, competitor-ad-teardown from Meta and Google ad libraries",
      "Content, SEO and ads: seo-content-audit, content-brief-factory, content-repurposer turns one asset into 10+ derivatives, google-ads-builder, ad-angle-miner",
      "Signals and sales ops: signal-scanner, funding-signal-monitor, sales-call-prep, meeting-brief, pipeline-review, sales-coaching",
      "Six full playbooks that chain skills into one command: Outbound Prospecting Engine, SEO Content Engine, Competitor Monitoring, Signal Detection, Event Prospecting, Client Onboarding",
    ],
    excerpt: "103 GTM skills for Claude Code, open source under MIT, that do the work instead of helping you brainstorm. Each skill is a folder with two files: SKILL.md, the step-by-step instructions Claude executes, and skill.meta.json, the registry metadata. There are three types: 33 capabilities (single-purpose tools), 61 composites (multi-step workflows), and 9 playbooks (end-to-end engines). Install one with npx goose-skills install competitor-intel, copy SKILL.md into your project's .claude/skills/ folder, then just describe the task. Claude loads the skill and runs the full workflow, no re-prompting. Requirements are Claude Code, Node.js, Python 3, plus Apify (free tier works) and Apollo API keys. For lead gen, apollo-lead-finder runs two-phase Apollo prospecting: first pass finds ICP matches, second pass enriches only the best with emails and phones, deduplicating against your existing Supabase leads so you never pay for the same contact twice. champion-tracker detects when your best customers change jobs. For outreach, cold-email-outreach selects leads, designs a 3-5 email sequence, writes personalized copy per recipient, and pushes to Smartlead, Instantly, or Lemlist. Signal-based skills chain real-world events: funding announced, qualify org against ICP, find decision-makers, write congrats plus value prop. Competitor intel includes battlecard-generator, which scrapes a competitor's website, G2 and Capterra reviews, ad libraries, and pricing into a sales battlecard. The six playbooks chain skills into one command each, including the Outbound Prospecting Engine: detect signals, research, find contacts, personalize, launch.",
    topMetrics: [
      { value: "103", label: "GTM skills" },
      { value: "9", label: "categories" },
      { value: "7", label: "playbooks" },
      { value: "30 min", label: "setup" },
    ],
    format: "pdf",
    date: "2026-05-11",
  },
  {
    slug: "loop-design-playbook",
    title: "Loop Design Playbook",
    metaTitle: "Loop Design Playbook for AI Agents | Muditek",
    metaDescription: "Turn AI coding agents into durable loops: trigger, state, worker, skills, verifier, halt. Templates, a 7-day rollout, and hard guardrails.",
    hook: "Stop prompting agents by hand and build loops that ship work while you are not watching.",
    whoItsFor: "Operators and founders running AI coding agents who want repeatable, verified automation instead of one-off prompts.",
    outcome: "Recurring work runs unattended with verification and spend caps, replacing manual prompting with no added headcount.",
    category: "agentic-engineering",
    keywords: ["AI agent loops","agentic engineering","loop design","AI coding agents","agent verification","loop spec","agent orchestration","AI automation"],
    whatsInside: [
      "The six-part production blueprint: trigger, state, worker, skills, verifier, halt, with the exact failure if each is missing",
      "The five-level ladder: ReAct, Goal, Ralph, Validator, and Orchestration loops, and why online arguments mix Level 2 with Level 5",
      "The smallest useful starter loop: pull-request babysitting, plus the /loop command to run it",
      "Three copy-paste templates: Loop Spec, Verifier Prompt, and Skill Card",
      "Four hard guardrails: iteration ceiling, no-progress detection, spend ceiling, and write-narrow permission boundaries",
      "A day-by-day first-week rollout with explicit exit conditions for each day",
      "The honest limits: do not loop weak work, do not let the worker grade itself, do not hide cost",
    ],
    excerpt: "A loop is not a vibe, a longer prompt, or a mystical agent swarm. It is a control system: a trigger, a worker, a verifier, state, budget, and a halt condition. The shift is role reversal. You stop being the person inside the loop typing the next prompt and become the person who writes the loop, owns the constraints, and decides what work deserves to run without you.\n\nThe production blueprint has six parts, and missing one means you are burning tokens with confidence. Trigger decides when the loop wakes (cron, webhook, pull request, Slack). State is what it knows between runs (repo, issues, memory files, queue). Worker is the agent that decides and acts (Claude Code, OpenClaw, Hermes, Codex). Skills are named procedures so the agent does not reinvent the business every run. Verifier checks output with tests, build, a reviewer model, a browser screenshot, or a human gate. Halt covers max iterations, no-progress detection, and a token or dollar ceiling, otherwise the loop becomes an invoice machine.\n\nStart small. The canonical first loop is pull-request babysitting: watch open PRs, fix build failures, address comments, rerun checks, and stop when the PR is green, blocked, or over budget. It works because the state is concrete, the verifier is obvious, and the blast radius is bounded.\n\nEvery serious loop needs three hard stops before live work: an iteration ceiling, no-progress detection (if two consecutive runs change nothing important, stop), and a spend ceiling capping tokens, dollars, or runtime. Then add permission boundaries: read broadly, write narrowly, ask before crossing. A loop with no verifier is just a confident generator.",
    topMetrics: [
      { value: "6", label: "parts in a production loop" },
      { value: "5", label: "levels on the loop ladder" },
      { value: "7", label: "day rollout plan" },
      { value: "3", label: "copy-paste templates" },
    ],
    format: "html",
    date: "2026-06-19",
  },
  {
    slug: "goal-playbook",
    title: "The /goal Playbook",
    metaTitle: "The /goal Playbook: Run an AI Coding Team | Muditek",
    metaDescription: "Assign a goal once, walk away, come back to finished work. How to write goals that finish, verify them, and run Codex, Claude Code and an orchestrator as one pipeline.",
    hook: "Assign a goal once, walk away, and come back to finished work instead of typing prompts one at a time.",
    whoItsFor: "Operators and founders who already use AI coding tools and want to delegate whole tasks to autonomous agents instead of steering every turn.",
    outcome: "You run an autonomous AI coding team from a single message, no added headcount, with verification baked in so the work is actually done.",
    category: "agentic-engineering",
    keywords: ["goal command","autonomous AI agents","agentic coding","Codex Claude Code orchestrator","AI agent orchestration","goal-oriented prompting","Hermes orchestrator","AI verification rule"],
    whatsInside: [
      "The prompting vs assigning shift: you define done, submit /goal once, the agent drives the loop",
      "The goal lifecycle: achieved, paused, blocked, cleared, or out of budget",
      "The full command set: /goal, /goal status, /goal pause, /goal resume, /goal clear, /subgoal, /handoff",
      "The 'done means' pattern plus strong vs weak goal examples and copy-paste templates",
      "The three roles: Orchestrator (Hermes), Builder (Codex), Reviewer (Claude Code), and why /goal lets them compose",
      "The verification rule: never trust the worker's self-report, run npm test and npm run build yourself",
      "Running multiple goals in parallel without two writers on one file (repos, branches, worktrees)",
      "A quick-start checklist from context to final review against your success criteria",
    ],
    excerpt: "A regular prompt asks an agent for the next response and you steer every turn. /goal flips that: you define the finished result, submit it once, and the agent drives toward it. The goal stays active until success criteria are met, you pause or clear it, it hits a block, or it runs out of turns. That is why it can run for minutes, hours, or overnight while you do something else.\n\nThe highest-leverage skill is writing a goal that finishes. The strongest pattern states the finish line as checkable conditions: \"Build the app described in SPEC.md. Done means tests pass, build passes, README is accurate, and git status only shows relevant project files.\" Every condition is verifiable, which makes the goal completable instead of open-ended. Weak goals like \"make something cool\" or \"improve my code\" fail because there is no success criteria.\n\nThe single most important rule: don't trust the worker's self-report as final, trust the verifier. Coding agents are confident. They will tell you the build passes when the build was never run, that tests pass when the tests never executed. So the orchestrator runs the checks itself (npm test, npm run build). Without verification, /goal is just a fancier prompt. With verification, it becomes a contract.\n\nIt scales across three roles that share nothing but the /goal format: Orchestrator (Hermes) decomposes and verifies, Builder (Codex) implements from spec, Reviewer (Claude Code) finds what is wrong. One message becomes a routed pipeline you watch move across a single board.",
    format: "html",
    date: "2026-05-24",
  },
  {
    slug: "ai-data-agent-guide",
    title: "AI Data Agent Guide",
    metaTitle: "How to Build an AI Data Agent | Muditek",
    metaDescription: "The exact 7-step architecture, stack, and self-healing loop behind replacing 4 analyst hires with one AI data agent that answers in Slack.",
    hook: "Replace 4 data analyst hires with one AI agent that answers questions instantly in Slack.",
    whoItsFor: "Operators and founders running a modern data stack (dbt, Snowflake/BigQuery) who are tired of analyst queues and want non-technical teams to self-serve answers without adding headcount.",
    outcome: "One AI data agent takes a question to a verified SQL answer, cutting an analyst team from 4-5 to 1 with no new hires.",
    category: "agentic-engineering",
    keywords: ["ai data agent","dbt semantic layer","context management","text-to-sql agent","claude agent sdk","self-healing agent","pgvector knowledge store","slack data agent"],
    whatsInside: [
      "The paradigm shift: kill the static semantic layer and replace it with a context sub-agent that reads your dbt models on-the-fly, per question",
      "Step 4, the context sub-agent that runs BEFORE SQL generation: reads model files, traces upstream dependencies, returns a structured brief of tables, columns, join paths, filters, dedup rules, caveats",
      "The self-healing knowledge store: user corrections (\"that metric needs this filter\") get stored as durable, reusable quirks via hybrid retrieval (pgvector + BM25 keyword search)",
      "Scoring every query on 3 dimensions: structural (does SQL parse), execution (does it run cleanly), context (does the answer match the question, via a Haiku semantic check)",
      "The 4-step recovery flow: context-gap brief, retry with targeted prompt, rerun context enrichment on schema mismatch, store human corrections as quirks",
      "Knowledge store config: collection weights, reviewed-item multiplier, reciprocal-rank fusion, fixed context budget",
      "The exact stack: Claude Opus 4.6 agent, Claude Agent SDK loop, dbt, Postgres + pgvector, OAI Embed 3-small, Slack interface, Notion answer storage",
    ],
    excerpt: "The modern data stack made data accessible to analysts. The AI data stack makes it accessible to everyone by replacing the human translation layer with an agent that goes from question to answer automatically. The core claim: the semantic layer is dead. Instead of a static, hand-maintained mapping between business concepts and SQL that breaks on every schema change, the agent reads your dbt models on-the-fly and builds its own brief per question. The semantic layer was \"the 20% of the data stack that was 80% of the pain.\" The build is 7 steps and took about 3 weeks end-to-end including Slack and Notion integrations. The critical step most teams skip is the context sub-agent (step 4): it runs BEFORE SQL generation, reads model files, traces upstream dependencies, checks application code, and returns a structured brief of tables, columns, join paths, filters, dedup rules, and caveats. Skip it and the agent hallucinates. Every query then runs a scoring and recovery loop: structural validation (does the SQL parse), execution checks (does it run with reasonable results), and a Haiku semantic check (does the answer match what was asked). When a user corrects the agent, that correction is stored as a durable \"quirk\" so it never repeats the same mistake. Results in production: hiring plan dropped from 4-5 data analysts to 1, 5x bandwidth across the function, and Sales, CS, Product, and Growth all self-serve answers in Slack with no tickets. Pick the right model: Opus 4.6 beats Codex 5.3 on data analysis despite losing on pure coding. Diagnosis first, figure out which analyst functions are automatable before building.",
    topMetrics: [
      { value: "4 to 1", label: "Analyst hires reduced" },
      { value: "5x", label: "Team bandwidth increase" },
      { value: "3 wks", label: "End-to-end build time" },
      { value: "$0", label: "Semantic layer maintenance" },
    ],
    format: "pdf",
    date: "2026-05-11",
  },
  {
    slug: "claude-dispatch-guide",
    title: "Claude Dispatch Setup Guide",
    metaTitle: "Claude Dispatch Setup Guide: Run AI From Your Phone | Muditek",
    metaDescription: "Set up Claude Dispatch and Remote Control, port your skills, and run AI workflows from your phone in under 10 minutes. Step by step.",
    hook: "Run real AI work from your phone while your desktop does the heavy lifting.",
    whoItsFor: "Operators and founders who already use Claude Desktop or Claude Code and want to trigger real work from their phone without sitting at the machine.",
    outcome: "Text a task from your phone, have it run on your own desktop with your files and tools, and get results back, saving 2 to 3 hours a day with no added headcount.",
    category: "agentic-engineering",
    keywords: ["claude dispatch","claude remote control","claude cowork","run ai from phone","claude code skills","scheduled tasks","claude desktop setup","agentic workflows"],
    whatsInside: [
      "The five-layer stack: Cowork engine, Plugins, Skills, Scheduled Tasks, and Dispatch, and how one message triggers all five",
      "Dispatch setup in about 5 minutes: download Claude Desktop, open Cowork (Cmd+2 on Mac), browse plugins, turn on code execution and file creation, pair with your phone",
      "Remote Control setup for Claude Code: requires v2.1.51+, run claude remote-control or /remote-control, scan the QR code from the mobile app",
      "Porting your existing Claude Code skills into Cowork from ~/.claude/skills/ or .claude/skills/ so they work with Dispatch",
      "Scheduled Tasks via /schedule or + New task: morning briefing, competitor watch, inbox cleaner, pipeline update",
      "Real phone-triggered workflows: lead scraping with parallel sub-agents, inbox cleaning that pre-drafts replies, thumbnail generation with face-swapping",
      "Why it beats OpenClaw: everything runs locally and sandboxed, allow-listing per action, flat monthly cost vs pay-per-token",
      "Pro tips: keep the computer awake, use Opus 4.6 + Extended Thinking, text replacement shortcuts, and voice-to-text dictation",
    ],
    excerpt: "Anthropic shipped two features that split Claude into two layers: your phone gives the orders, your desktop does the work. The work still happens on your computer, you just do not need to be sitting at it. Dispatch is for Cowork (text Claude a task from your phone, it runs on your desktop with local files and tools, results come back). Remote Control is for Claude Code (start a session at your desk, pick it up from your phone anywhere). Both require your computer to stay awake, so many people run a dedicated Mac Mini 24/7.\n\nDispatch is not standalone. It is the remote for a full agent system: Cowork (the engine that reads and writes files, builds spreadsheets, runs sub-agents, connects to Drive, Gmail, Slack and 50+ tools), Plugins (one-click skill bundles), Skills (folders of scripts and templates that teach Claude your specific tasks), and Scheduled Tasks (describe once, set frequency, runs on repeat). Send \"Compile my weekly sales report\" and Dispatch routes it to your desktop, Cowork starts a session, the plugin connects to Sheets and CRM, the skill formats the report your way, and the finished doc lands on your phone.\n\nSetup takes about 5 minutes: download Claude Desktop, open Cowork (Cmd+2 on Mac), Browse plugins, then Settings > Capabilities to turn on Code execution and file creation. Find Dispatch in the sidebar, Get started, grant permissions, then pair the mobile app. For Remote Control you need Claude Code v2.1.51+, run claude remote-control, press spacebar to show a QR code, and scan it. Real workflows: scrape 200 agency owners with parallel sub-agents, run inbox cleaner, recreate a thumbnail with your face.",
    topMetrics: [
      { value: "2-3 hrs", label: "saved per day" },
      { value: "under 10 min", label: "to full setup" },
      { value: "5 layers", label: "one message triggers" },
      { value: "4-8x", label: "cheaper than OpenClaw" },
    ],
    format: "pdf",
    date: "2026-05-11",
  },
  {
    slug: "cowork-setup-guide",
    title: "Claude Cowork Setup Guide",
    metaTitle: "Claude Cowork Setup Guide: Install to Output | Muditek",
    metaDescription: "Set up Claude Cowork the right way. Build a 4-folder context system, paste global instructions, and ship real deliverables in 30 minutes.",
    hook: "Go from installing Claude Cowork to your first real deliverable in 30 minutes.",
    whoItsFor: "Operators, founders, and knowledge workers who switched to Claude but still only use Chat and never touch Cowork.",
    outcome: "Claude reads your files, sounds like you, and ships real deliverables into a folder with 10-word prompts and no added headcount.",
    category: "agentic-engineering",
    keywords: ["claude cowork","claude desktop setup","context folder","global instructions","askuserquestion","claude plugins","agentic workflow","claude for non-coders"],
    whatsInside: [
      "Step 1: install Claude Desktop, open the Cowork tab, and always select Opus 4.6 plus Extended thinking",
      "Step 2: build a 4-folder context system (ABOUT ME, TEMPLATES, PROJECTS, CLAUDE OUTPUTS) where only one folder is writable",
      "The two files that go in ABOUT ME: about-me.md and anti-ai-writing-style.md (no em dashes, no filler)",
      "Step 3: the exact global instructions block to paste once (folder protocol, naming convention, operating rules)",
      "Step 4: the master prompt template that runs 80% of sessions plus a Mac text-replacement shortcut to auto-paste it",
      "How AskUserQuestion makes Claude generate clickable forms so it prompts you instead of you prompting it",
      "Step 5 and 6: install the 11 official plugins (Marketing, Legal, Data, Sales, Finance) and connect tools like Slack, Gmail, Notion",
      "Four real use cases: newsletters, client deliverables, competitive analysis, and automated weekly briefings via /schedule",
    ],
    excerpt: "Cowork is a mode inside the Claude desktop app. It reads files from a folder on your computer, learns how you work, and produces real output directly into that folder. Most people who switched to Claude never touch it. This guide fixes that in four steps. Install: download Claude Desktop, click the Cowork tab between Chat and Code, and always select Opus 4.6 with Extended thinking on. Build the context folder: four subfolders, clean and intentional. ABOUT ME holds two files, about-me.md (who you are, priorities, voice) and anti-ai-writing-style.md (no em dashes, no filler, no \"certainly\"). TEMPLATES holds finished work so good you reuse the structure. PROJECTS holds one subfolder per active project with briefs and drafts. CLAUDE OUTPUTS is the only folder where Claude writes. Set global instructions once in Settings, including the folder protocol (three read-only folders, one write folder), a naming convention (project_content-type_v1.ext), and operating rules (\"If the brief is unclear, use AskUserQuestion. No filler. Deliver the work.\"). Then the master prompt: \"I want to [TASK] to [SUCCESS CRITERIA]. First, explore my CLAUDE COWORK folder. Then, ask me questions using the AskUserQuestion tool. I want to refine the approach before you execute.\" Claude reads your context, generates a clickable form with buttons and multi-select, shows a plan, and writes real files. Combined with context files, prompts can be 10 words long and still sound like you. The guide closes with four shipped use cases: newsletters, client deliverables, competitive analysis comparison tables, and automated weekly briefings that run every Monday via /schedule without you being there.",
    topMetrics: [
      { value: "30 min", label: "Install to first deliverable" },
      { value: "4", label: "Context folders to set up" },
      { value: "10 words", label: "Prompt length that still sounds like you" },
      { value: "11", label: "Official plugins to install" },
    ],
    format: "pdf",
    date: "2026-05-11",
  },
  {
    slug: "sequoia-autopilot-playbook",
    title: "The Autopilot Playbook",
    metaTitle: "The Autopilot Playbook: Sell Work, Not Tools | Muditek",
    metaDescription: "Why the next trillion-dollar company sells the work, not software. The autopilot thesis, a 10-vertical $1T+ map, and where to wedge in first.",
    hook: "The next trillion-dollar company won't sell software. It will sell the work that software makes possible.",
    whoItsFor: "Founders and operators building AI products who are tired of racing the model, and want to capture the work budget instead of the tool budget.",
    outcome: "A clear thesis and vertical map for selling outcomes (the work) instead of tools, so AI replaces real labor spend with no added headcount.",
    category: "agentic-engineering",
    keywords: ["autopilot vs copilot","AI agents replace work","services as software","outcome-based AI","Sequoia AI thesis","work budget vs tool budget","AI vertical TAM","agentic engineering"],
    whatsInside: [
      "Copilots vs Autopilots: a side-by-side on what each sells, who buys, and why next model kills the copilot but strengthens the autopilot",
      "The $6 market math: for every $1 on software, $6 goes to services, and autopilots capture that work budget from day one",
      "Intelligence vs Judgement: why software engineering crossed the autonomy line first and every profession is next",
      "Outsourcing as the wedge: the 3 signals (accepted external delivery, existing budget line, outcome-based buying) that mark a task ready to be replaced",
      "From wedge to platform: Crosby starting with NDAs as the intelligence-heavy entry into $20-25B transactional legal",
      "The $1T+ map across 10 verticals with TAM, why-now, and who's-winning per category",
      "The Innovator's Dilemma: why copilots like Harvey can't become autopilots without cannibalizing their own law-firm customers",
    ],
    excerpt: "The thesis: stop selling tools, start selling the work. A company pays $10K a year for QuickBooks and $120K for an accountant to close the books. The next legendary company will just close the books. If you sell the tool, you race the model. If you sell the work, every model improvement makes your service faster, cheaper, and harder to compete with. The split is intelligence vs judgement. Writing code is mostly intelligence, complex rules that AI can now do autonomously. Software engineering crossed that line first, and it is coming to every profession. Copilots sell the tool to the professional and compete on features. Autopilots sell the outcome to the company directly and compete on results delivered. The work budget dwarfs the tool budget, six to one. Where to start: outsourcing. If a task is already outsourced, it tells you three things. Accepted external delivery (they already let outsiders do it), an existing budget line you can substitute cleanly (a vendor swap, not a reorg), and outcome-based buying (they buy the result, not the tool). Start with the outsourced, intelligence-heavy task, nail distribution, then expand into insourced judgement-heavy work as AI compounds. Crosby started with NDAs, the wedge, against a $20-25B transactional legal TAM. The map covers 10 verticals worth $1T+ combined: recruitment ($200B+), supply chain ($200B+), insurance brokerage ($140-200B), accounting (lost 340K accountants in 5 years, 75% of CPAs retiring), healthcare revenue cycle, claims adjusting, tax advisory, transactional legal. The higher the intelligence ratio, the sooner autopilots win.",
    topMetrics: [
      { value: "$1T+", label: "Combined TAM across 10 mapped verticals" },
      { value: "6:1", label: "Services dollars spent for every software dollar" },
      { value: "340K", label: "Accountants lost in the US over 5 years" },
      { value: "75%", label: "Of CPAs nearing retirement" },
    ],
    format: "pdf",
    date: "2026-05-11",
  },
  {
    slug: "judgment-moat",
    title: "The Judgment Moat",
    metaTitle: "The Judgment Moat: Skill Files vs AI Wrappers | Muditek",
    metaDescription: "How a 2-person law firm encoded its expert judgment into 6 skill files and now outworks firms with 1,000+ lawyers. The framework, step by step.",
    hook: "Six skill files that encode your best operator's judgment beat a thousand specialists running the same wrapper.",
    whoItsFor: "B2B founders and operators who see AI wrappers commoditizing and want a defensible moat: their own expert judgment encoded into systems that run autonomously, with no added headcount.",
    outcome: "Turn one expert's judgment into installable skill files that give your whole team day-one consistency at your highest standard, without hiring.",
    category: "agentic-engineering",
    keywords: ["encoded judgment","ai skill files","ai wrappers","agentic engineering","claude skills","legal ai automation","competitive moat ai","b2b ai systems"],
    whatsInside: [
      "The wrapper trap: why Harvey, Kensho, and Gong all run the same foundation models and sell the same templates every firm already has",
      "The real gap: model and interface commoditize, only whose judgment is encoded in the instructions is defensible",
      "Case study breakdown of the lawyer's 6 skill files: Contract Review (4 modes, severity ratings, market-term benchmarking), Tracked Changes (XML-level Word edits), Self-Review Loop, parallel Legal Research, Client Comms, Policy Writing",
      "Three real results: 40-page redline in under an hour, a night-before acquisition saved by finding 2 contradictions in the buyer's own disclosures, a 48-hour breach demand neutralized",
      "The 4-step framework: audit your expert judgment, encode it into plain-text skill files, add a self-review loop, deploy across your team",
      "Why a self-review loop catches hallucinated citations before they ship",
    ],
    excerpt: "Every industry has its AI wrappers. Legal has Harvey, finance has Kensho, sales has Gong. They all run on the same foundation models, and the templates they sell are the same ones every firm already has. That is not a moat. The model commoditizes. The interface commoditizes. The only thing that does not is whose judgment is encoded in the instructions.\n\nA lawyer proved it. He built 6 skill files encoding his judgment into Claude, and his 2-person firm now routinely outworks firms with 1,000+ lawyers. The skills: Contract Review with 4 modes, severity ratings, and market-term benchmarking. Tracked Changes done at the XML level inside Word, so opposing counsel never knows. A Self-Review Loop that catches hallucinated citations before they ship. Legal Research run across parallel angles simultaneously, not sequentially. Client Comms drafted to match his tone per relationship. Policy Writing with jurisdiction-specific requirements baked in.\n\nThe results are not hypothetical. A 40-page redline in under an hour, 30 minutes of which was thinking, not typing. A night-before acquisition saved by finding 2 contradictions in the buyer's own disclosures, deal closed the next morning. A 48-hour breach demand neutralized after the system found 2 of 4 claimed breaches referenced obligations the counterparty had modified in its own side letter.\n\nThe framework applies to legal, finance, operations, revenue. Audit what your best person knows that no template captures. Encode it into plain-text markdown skill files. Add a self-review loop. Deploy across the team so everyone runs at your highest standard from day one.",
    topMetrics: [
      { value: "6", label: "Skill files" },
      { value: "2", label: "Person firm vs 1,000+ lawyers" },
      { value: "<1h", label: "40-page redline" },
      { value: "30 min", label: "Of that was thinking, not typing" },
    ],
    format: "pdf",
    date: "2026-05-11",
  },
  {
    slug: "mudiagent-operator-guide",
    title: "MudiAgent Operator Guide",
    metaTitle: "MudiAgent Operator Guide: Run an Agent Team | Muditek",
    metaDescription: "Operate MudiAgent from one agent on your laptop to an automated agent team on a VPS you run from your phone. Architecture, levels, and setup.",
    hook: "Run a marketing department from your terminal with an agent team that shows up to work on its own.",
    whoItsFor: "Operators and founders who want AI agents to run real marketing workflows end to end, not just answer questions, without adding headcount.",
    outcome: "An automated agent team on infrastructure you control that runs SEO, outbound, and content workflows on a schedule and only pings you for decisions that need taste.",
    category: "agentic-engineering",
    keywords: ["MudiAgent operator guide","AI agent team","autonomous agent VPS","agent control room","SEO agent pipeline","agent orchestrator","specialist agents","agentic engineering"],
    whatsInside: [
      "What MudiAgent is: 123 bundled skills, 70+ gateway tools, 300+ models, 6 deployment targets, 20+ messaging surfaces",
      "The brain, personality, skillset model: MEMORY.md and USER.md, SOUL.md, and a self-writing skills library",
      "The SEO agent walkthrough: 21 steps from keyword seed to published article in one Docker container, plus why one container not three",
      "The four-part mental model: you, the control room at /root/vps-agents, the specialist agents, and the optional task bus",
      "The storage split: control room docs (no raw secrets) vs /srv/<agent>/data live runtime",
      "Levels 1 to 4: one agent, direct specialists, orchestrator and specialists, automated team on cron",
      "The automated setup flow: Hetzner API key, create-vps, setup-control-room, agent-control-room skills in 10 to 15 minutes",
      "Prototype to production: prototype, run 2-3 times correcting drift, fine-tune, deploy autonomous on a VPS",
    ],
    excerpt: "MudiAgent runs your workflows end to end. It navigates your browser, executes terminal commands, schedules cron jobs, monitors inboxes, drafts the work, and posts results to Telegram, Discord, Slack, or email. Every agent has three parts: a brain (memory at ~/.mudiagent/memories/, with MEMORY.md and USER.md injected at session start, sessions stored in SQLite), a personality (SOUL.md, where you set concise, blunt, or formal voice), and a skillset (123 skills out of the box, plus a closed learning loop where the agent writes new skills as it works). The day-one rule: do not write your own skills, run real work and let the harness write them.\n\nThe setup grows through four levels. Level 1 is one agent. Level 2 is direct specialist agents (seo, dev, cmo) you talk to individually. Level 3 adds an orchestrator as a front door that reads the control room and routes work. Level 4 is an automated team where weekly SEO reports run on cron, server health checks fire daily, and backups verify themselves.\n\nThe SEO agent shows the shape: five layers in one Docker container, 21 steps across research and ideate, production, and distribution. One container because SEO work is sequential and every step needs memory of what was decided upstream. The storage split matters: /root/vps-agents holds docs, rules, and runbooks with no raw secrets, while /srv/<agent>/data holds the live runtime. You can rebuild the body from the brain, not the brain from the body.",
    topMetrics: [
      { value: "123", label: "Bundled skills out of the box" },
      { value: "300+", label: "Models through one subscription" },
      { value: "21", label: "Steps in the SEO pipeline" },
      { value: "4", label: "Levels from one agent to a fleet" },
    ],
    format: "html",
    date: "2026-05-18",
  },
];

export const PLAYBOOK_SLUGS = PLAYBOOKS.map((p) => p.slug);

export function getPlaybook(slug: string): Playbook | undefined {
  return PLAYBOOKS.find((p) => p.slug === slug);
}
