"use client";

import { useState, type FormEvent, type ReactNode } from "react";
import { TrackedSourceLink } from "@/components/acquisition-tracking";
import { findProspectingTools, type ProspectingTool } from "@/lib/tools/prospecting-data";
import { findPublicSignals, type PublicSignal, type SignalIndustry } from "@/lib/tools/signal-data";
import { buildQualifiedMeetingSpecification, type QualifiedMeetingInput } from "@/lib/tools/qualified-meeting";
import { countSpfDnsMechanisms, makeDmarcRecord, makeSpfRecord } from "@/lib/tools/dns";
import type { CmsFacility } from "@/lib/tools/cms";
import { useToolTracking } from "@/components/tools/use-tool-tracking";

const FIELD = "mt-2 min-h-11 w-full rounded-[10px] border border-white/[0.14] bg-white/[0.035] px-3 py-2.5 text-sm text-foreground outline-none focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-primary/35";
const LABEL = "text-sm font-bold text-foreground/80";
const BUTTON = "min-h-12 bg-primary px-6 py-3 text-sm font-black text-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-foreground focus-visible:ring-offset-4 focus-visible:ring-offset-background disabled:opacity-50";
const PANEL = "rounded-xl border border-white/[0.09] bg-card/55 p-5 md:p-8";

function ToolGrid({ children }: { children: ReactNode }) {
  return <div className="grid gap-8 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]">{children}</div>;
}

function ResultPlaceholder({ children }: { children: ReactNode }) {
  return <p className="text-sm leading-6 text-foreground/60">{children}</p>;
}

function SourceLink({ href, asset, children }: { href: string; asset: string; children: ReactNode }) {
  return <TrackedSourceLink href={href} asset={asset} placement="tool-result-source" className="text-primary underline decoration-primary/35 underline-offset-4 hover:decoration-primary">{children}</TrackedSourceLink>;
}

export function SalesProspectingToolFinder() {
  const [selected, setSelected] = useState<ProspectingTool["workflows"]>([]);
  const [results, setResults] = useState<ProspectingTool[] | null>(null);
  const tracking = useToolTracking("sales-prospecting-tool-finder");
  const options: Array<[ProspectingTool["workflows"][number], string]> = [["people", "People and job titles"], ["companies", "Company records"], ["local", "Local businesses"], ["technology", "Website technology"], ["funding", "Funding events"]];
  function submit(event: FormEvent) {
    event.preventDefault();
    setResults(findProspectingTools(selected));
    tracking.complete();
  }
  return <ToolGrid><form onSubmit={submit} onChange={tracking.start} className={PANEL}><h2 className="text-2xl font-black">What must the source contain?</h2><fieldset className="mt-6 grid gap-3"><legend className="sr-only">Required prospect data</legend>{options.map(([value, label]) => <label key={value} className="flex min-h-11 items-center gap-3 border border-white/[0.1] p-3 text-sm"><input type="checkbox" checked={selected.includes(value)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, value] : current.filter((item) => item !== value))} />{label}</label>)}</fieldset><button className={`${BUTTON} mt-6`} disabled={!selected.length}>Find tools</button></form><section aria-live="polite" className={PANEL}><h2 className="text-2xl font-black">Matching sources</h2><div className="mt-5 space-y-4">{results === null ? <ResultPlaceholder>Select the evidence you need. Results come from a fixed, sourced list and are not ranked.</ResultPlaceholder> : results.length === 0 ? <ResultPlaceholder>No listed tool covers every selected requirement. Split the workflow or verify another provider directly.</ResultPlaceholder> : results.map((tool) => <article key={tool.name} className="border-t border-white/[0.09] pt-4 first:border-0 first:pt-0"><h3 className="font-bold">{tool.name}</h3><p className="mt-2 text-sm leading-6 text-foreground/65">{tool.description}</p><p className="mt-3 flex gap-4 text-sm"><SourceLink href={tool.sourceUrl} asset="sales-prospecting-tool-finder">Product source</SourceLink><SourceLink href={tool.pricingUrl} asset="sales-prospecting-tool-finder">Current pricing</SourceLink></p><p className="mt-2 text-xs text-foreground/45">Checked {tool.lastChecked}</p></article>)}</div></section></ToolGrid>;
}

export function PublicB2BSignalFinder() {
  const [industry, setIndustry] = useState<SignalIndustry | "">("");
  const [results, setResults] = useState<PublicSignal[] | null>(null);
  const tracking = useToolTracking("public-b2b-signal-finder");
  function submit(event: FormEvent) { event.preventDefault(); if (!industry) return; setResults(findPublicSignals(industry)); tracking.complete(); }
  return <ToolGrid><form onSubmit={submit} onChange={tracking.start} className={PANEL}><label className={LABEL}>Market<select className={FIELD} value={industry} onChange={(event) => setIndustry(event.target.value as SignalIndustry)} required><option value="">Choose a market</option><option value="general-b2b">General B2B</option><option value="ma">M&amp;A services</option><option value="healthcare-staffing">Healthcare staffing</option><option value="freight">Freight</option></select></label><p className="mt-5 text-sm leading-6 text-foreground/60">A signal is a public fact that helps prioritize research. It does not prove intent, budget, or qualification.</p><button className={`${BUTTON} mt-6`}>Show public signals</button></form><section aria-live="polite" className={PANEL}><h2 className="text-2xl font-black">Research paths</h2><div className="mt-5 space-y-5">{results === null ? <ResultPlaceholder>Choose a market to see relevant public sources and safe ways to use them.</ResultPlaceholder> : results.map((signal) => <article key={signal.label} className="border-t border-white/[0.09] pt-4 first:border-0 first:pt-0"><h3 className="font-bold">{signal.label}</h3><p className="mt-2 text-sm text-foreground/70">Observed fact: {signal.observation}</p><p className="mt-2 text-sm leading-6 text-foreground/60">{signal.use}</p><p className="mt-3 text-sm"><SourceLink href={signal.sourceUrl} asset="public-b2b-signal-finder">{signal.sourceName}</SourceLink></p></article>)}</div></section></ToolGrid>;
}

type DnsPayload = Record<string, unknown> & { error?: string; found?: boolean; query?: string; records?: string[]; lookupCount?: number; lookupLimitExceeded?: boolean; checkedDomains?: string[]; cycles?: string[] };

function DnsResult({ payload }: { payload: DnsPayload | null }) {
  if (!payload) return <ResultPlaceholder>Enter the requested DNS information. Results show published records only.</ResultPlaceholder>;
  if (payload.error) return <p role="alert" className="text-sm text-red-300">{payload.error}</p>;
  if ("mx" in payload || "spf" in payload || "dmarc" in payload) {
    const auth = payload as { mx?: DnsPayload; spf?: DnsPayload; dmarc?: DnsPayload; dkim?: DnsPayload | null; dkimNote?: string };
    const checks: Array<[string, DnsPayload | null | undefined]> = [["MX", auth.mx], ["SPF", auth.spf], ["DMARC", auth.dmarc], ["DKIM", auth.dkim]];
    return <div className="space-y-5">{checks.map(([label, result]) => <section key={label} className="border-t border-white/[0.09] pt-4 first:border-0 first:pt-0"><div className="flex items-center justify-between gap-4"><h3 className="font-bold">{label}</h3><span className={`text-xs font-bold ${result?.found ? "text-emerald-300" : "text-amber-300"}`}>{result?.found ? "Record found" : label === "DKIM" && !result ? "Not checked" : "Not found"}</span></div>{result?.records?.map((record) => <pre key={record} className="mt-3 overflow-auto whitespace-pre-wrap break-all rounded-lg bg-black/25 p-3 text-xs leading-5">{record}</pre>)}{label === "SPF" && typeof result?.lookupCount === "number" ? <p className={`mt-3 text-xs ${result.lookupLimitExceeded ? "text-amber-300" : "text-foreground/55"}`}>DNS mechanisms counted across inspected SPF records: {result.lookupCount}{result.lookupLimitExceeded ? ". This exceeds SPF's limit of 10." : "."}</p> : null}</section>)}{auth.dkimNote ? <p className="text-xs leading-5 text-foreground/50">{auth.dkimNote}</p> : null}</div>;
  }
  return <div><p className={`text-sm font-bold ${payload.found ? "text-emerald-300" : "text-amber-300"}`}>{payload.found ? "Public record found." : "No matching public record found."}</p>{payload.records?.map((record) => <pre key={record} className="mt-4 overflow-auto whitespace-pre-wrap break-all rounded-lg bg-black/25 p-4 text-xs leading-6">{record}</pre>)}{typeof payload.lookupCount === "number" ? <div className="mt-4 text-sm leading-6 text-foreground/65"><p>DNS mechanisms counted across inspected SPF records: {payload.lookupCount}</p>{payload.lookupLimitExceeded ? <p className="text-amber-300">This exceeds SPF&apos;s limit of 10 DNS-querying mechanisms. Verify the record before use.</p> : null}{payload.cycles?.length ? <p className="text-amber-300">Cycle detected: {payload.cycles.join(", ")}</p> : null}<p>Domains inspected: {payload.checkedDomains?.join(", ")}</p></div> : null}</div>;
}

function DnsChecker({ slug, type, needsSelector = false, auth = false }: { slug: string; type: "spf" | "dmarc" | "dkim" | "auth"; needsSelector?: boolean; auth?: boolean }) {
  const [domain, setDomain] = useState("");
  const [selector, setSelector] = useState("");
  const [result, setResult] = useState<DnsPayload | null>(null);
  const [loading, setLoading] = useState(false);
  const tracking = useToolTracking(slug);
  async function submit(event: FormEvent) {
    event.preventDefault(); setLoading(true); setResult(null); tracking.start();
    try {
      const params = new URLSearchParams({ domain, type }); if (selector) params.set("selector", selector);
      const response = await fetch(`/api/tools/dns?${params}`); const payload = await response.json() as DnsPayload; setResult(payload); if (response.ok) tracking.complete();
    } catch { setResult({ error: "The DNS request failed. Try again." }); } finally { setLoading(false); }
  }
  return <ToolGrid><form onSubmit={submit} className={PANEL}><label className={LABEL}>Domain<input className={FIELD} value={domain} onChange={(event) => setDomain(event.target.value)} placeholder="example.com" required /></label>{needsSelector || auth ? <label className={`${LABEL} mt-5 block`}>DKIM selector {auth ? "(optional)" : ""}<input className={FIELD} value={selector} onChange={(event) => setSelector(event.target.value)} placeholder="Provider-supplied selector" required={needsSelector} /></label> : null}<button className={`${BUTTON} mt-6`} disabled={loading}>{loading ? "Checking…" : "Check public DNS"}</button><p className="mt-4 text-xs leading-5 text-foreground/50">This checks published DNS records. It does not test inbox placement or predict deliverability.</p></form><section aria-live="polite" className={PANEL}><h2 className="text-2xl font-black">Published result</h2><div className="mt-5"><DnsResult payload={result} /></div></section></ToolGrid>;
}

export function EmailAuthenticationChecker() { return <DnsChecker slug="email-authentication-checker" type="auth" auth />; }
export function DmarcChecker() { return <DnsChecker slug="dmarc-checker" type="dmarc" />; }
export function DkimChecker() { return <DnsChecker slug="dkim-checker" type="dkim" needsSelector />; }
export function SpfChecker() { return <DnsChecker slug="spf-checker" type="spf" />; }

export function DmarcGenerator() {
  const [policy, setPolicy] = useState<"" | "none" | "quarantine" | "reject">(""); const [pct, setPct] = useState(""); const [rua, setRua] = useState(""); const [ruf, setRuf] = useState(""); const [result, setResult] = useState(""); const tracking = useToolTracking("dmarc-generator");
  function submit(event: FormEvent) { event.preventDefault(); if (!policy || pct === "") return; setResult(makeDmarcRecord({ policy, percentage: Number(pct), aggregateEmail: rua, forensicEmail: ruf })); tracking.complete(); }
  return <ToolGrid><form onSubmit={submit} onChange={tracking.start} className={PANEL}><label className={LABEL}>Policy<select className={FIELD} value={policy} onChange={(event) => setPolicy(event.target.value as typeof policy)} required><option value="">Choose a policy</option><option value="none">Monitor only: none</option><option value="quarantine">Quarantine</option><option value="reject">Reject</option></select></label><label className={`${LABEL} mt-5 block`}>Percentage<input type="number" min="0" max="100" className={FIELD} value={pct} onChange={(event) => setPct(event.target.value)} required /></label><label className={`${LABEL} mt-5 block`}>Aggregate report email (optional)<input type="email" className={FIELD} value={rua} onChange={(event) => setRua(event.target.value)} /></label><label className={`${LABEL} mt-5 block`}>Forensic report email (optional)<input type="email" className={FIELD} value={ruf} onChange={(event) => setRuf(event.target.value)} /></label><button className={`${BUTTON} mt-6`} disabled={!policy || pct === ""}>Generate record</button></form><section aria-live="polite" className={PANEL}><h2 className="text-2xl font-black">TXT value</h2>{result ? <><pre className="mt-5 whitespace-pre-wrap break-all rounded-lg bg-black/25 p-4 text-sm">{result}</pre><p className="mt-4 text-sm text-foreground/60">Publish at <code>_dmarc.yourdomain.com</code>. Validate the rollout with your email administrator before enforcement.</p></> : <div className="mt-5"><ResultPlaceholder>Choose explicit policy settings. The generator does not decide which policy is safe for your domain.</ResultPlaceholder></div>}</section></ToolGrid>;
}

export function SpfGenerator() {
  const [includes, setIncludes] = useState(""); const [ip4, setIp4] = useState(""); const [ip6, setIp6] = useState(""); const [policy, setPolicy] = useState<"" | "-all" | "~all" | "?all">(""); const [result, setResult] = useState(""); const [error, setError] = useState(""); const tracking = useToolTracking("spf-generator");
  const lines = (value: string) => value.split(/[\s,]+/).map((item) => item.trim()).filter(Boolean);
  function submit(event: FormEvent) { event.preventDefault(); const record = makeSpfRecord(lines(includes), lines(ip4), lines(ip6), policy); if (!record) { setResult(""); setError("Use valid include domains, IP addresses, CIDR ranges, and an explicit policy."); return; } setError(""); setResult(record); tracking.complete(); }
  const count = result ? countSpfDnsMechanisms(result) : 0;
  return <ToolGrid><form onSubmit={submit} onChange={tracking.start} className={PANEL}><label className={LABEL}>Provider include domains<textarea className={`${FIELD} min-h-24`} value={includes} onChange={(event) => setIncludes(event.target.value)} placeholder="One provider-supplied include domain per line" /></label><label className={`${LABEL} mt-5 block`}>IPv4 mechanisms<textarea className={`${FIELD} min-h-20`} value={ip4} onChange={(event) => setIp4(event.target.value)} placeholder="One address or CIDR range per line" /></label><label className={`${LABEL} mt-5 block`}>IPv6 mechanisms<textarea className={`${FIELD} min-h-20`} value={ip6} onChange={(event) => setIp6(event.target.value)} /></label><label className={`${LABEL} mt-5 block`}>All policy<select className={FIELD} value={policy} onChange={(event) => setPolicy(event.target.value as typeof policy)} required><option value="">Choose a policy</option><option value="~all">Soft fail: ~all</option><option value="-all">Fail: -all</option><option value="?all">Neutral: ?all</option></select></label><button className={`${BUTTON} mt-6`} disabled={!policy}>Generate record</button>{error ? <p role="alert" className="mt-4 text-sm text-red-300">{error}</p> : null}</form><section aria-live="polite" className={PANEL}><h2 className="text-2xl font-black">SPF value</h2>{result ? <><pre className="mt-5 whitespace-pre-wrap break-all rounded-lg bg-black/25 p-4 text-sm">{result}</pre><p className="mt-4 text-sm text-foreground/60">Direct DNS-querying mechanisms in this record: {count}. Nested provider lookups are not counted here. Check the published record before use.</p></> : <div className="mt-5"><ResultPlaceholder>Copy include domains only from each sending provider&apos;s current documentation.</ResultPlaceholder></div>}</section></ToolGrid>;
}

const INITIAL_SPEC: QualifiedMeetingInput = { companyFit: "", buyerRoles: "", requiredProblem: "", timing: "", attendance: "held", exclusions: "", noShowPolicy: "", disputeWindow: "" };
export function QualifiedMeetingSpecificationBuilder() {
  const [values, setValues] = useState(INITIAL_SPEC); const [result, setResult] = useState(""); const [error, setError] = useState(""); const tracking = useToolTracking("qualified-meeting-specification-builder");
  function submit(event: FormEvent) { event.preventDefault(); const next = buildQualifiedMeetingSpecification(values); if (!next) { setError("Complete every required rule."); return; } setError(""); setResult(next); tracking.complete(); }
  function download() { const url = URL.createObjectURL(new Blob([result], { type: "text/markdown" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "qualified-meeting-specification.md"; anchor.click(); URL.revokeObjectURL(url); }
  const fields: Array<[keyof QualifiedMeetingInput, string, string]> = [["companyFit", "Company fit", "Industries, size, geography, and hard requirements"], ["buyerRoles", "Accepted buyer roles", "Named functions or authority"], ["requiredProblem", "Required problem or project", "What the buyer must confirm"], ["timing", "Timing requirement", "The agreed planning or buying window"], ["exclusions", "Exclusions", "Clients, competitors, disallowed accounts, or situations"], ["noShowPolicy", "No-show and reschedule rule", "Exactly when a no-show becomes billable, replaceable, or excluded"], ["disputeWindow", "Dispute process", "Evidence and time allowed to dispute qualification"]];
  return <ToolGrid><form onSubmit={submit} onChange={tracking.start} className={PANEL}><div className="grid gap-5">{fields.map(([key, label, placeholder]) => <label key={key} className={LABEL}>{label}{key === "exclusions" ? " (optional)" : ""}<textarea className={`${FIELD} min-h-20`} value={values[key]} onChange={(event) => setValues((current) => ({ ...current, [key]: event.target.value }))} placeholder={placeholder} required={key !== "exclusions"} /></label>)}<label className={LABEL}>Attendance requirement<select className={FIELD} value={values.attendance} onChange={(event) => setValues((current) => ({ ...current, attendance: event.target.value as "held" | "booked" }))}><option value="held">Buyer must attend</option><option value="booked">Buyer must book</option></select></label></div><button className={`${BUTTON} mt-6`}>Build specification</button>{error ? <p role="alert" className="mt-4 text-sm text-red-300">{error}</p> : null}</form><section aria-live="polite" className={PANEL}><h2 className="text-2xl font-black">Agreement draft</h2>{result ? <><pre className="mt-5 max-h-[700px] overflow-auto whitespace-pre-wrap text-sm leading-7 text-foreground/75">{result}</pre><button type="button" onClick={download} className={`${BUTTON} mt-6`}>Download Markdown</button></> : <div className="mt-5"><ResultPlaceholder>Write one definition that both buyer and provider can test against evidence.</ResultPlaceholder></div>}</section></ToolGrid>;
}

export function CmsHealthcareStaffingExplorer() {
  const [state, setState] = useState(""); const [name, setName] = useState(""); const [minBeds, setMinBeds] = useState(""); const [facilities, setFacilities] = useState<CmsFacility[] | null>(null); const [error, setError] = useState(""); const [note, setNote] = useState(""); const [loading, setLoading] = useState(false); const tracking = useToolTracking("cms-healthcare-staffing-explorer");
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); setFacilities(null); tracking.start(); try { const params = new URLSearchParams({ state, name, minBeds: minBeds || "0" }); const response = await fetch(`/api/tools/cms-facilities?${params}`); const payload = await response.json() as { facilities?: CmsFacility[]; error?: string; note?: string }; if (!response.ok) setError(payload.error ?? "CMS data is unavailable."); else { setFacilities(payload.facilities ?? []); setNote(payload.note ?? ""); tracking.complete(); } } catch { setError("CMS data is unavailable. Try again later."); } finally { setLoading(false); } }
  return <div><form onSubmit={submit} className={`${PANEL} grid gap-5 md:grid-cols-3 md:items-end`}><label className={LABEL}>US state<input className={FIELD} value={state} onChange={(event) => setState(event.target.value.toUpperCase().slice(0, 2))} placeholder="CA" pattern="[A-Za-z]{2}" required /></label><label className={LABEL}>Facility name (optional)<input className={FIELD} value={name} onChange={(event) => setName(event.target.value)} /></label><label className={LABEL}>Minimum certified beds (optional)<input className={FIELD} type="number" min="0" max="10000" value={minBeds} onChange={(event) => setMinBeds(event.target.value)} /></label><button className={BUTTON} disabled={loading}>{loading ? "Searching CMS…" : "Search CMS records"}</button><p className="text-xs leading-5 text-foreground/50 md:col-span-2">The tool searches up to 2,000 official CMS provider records for the state and displays at most 20 matches. Missing values stay missing.</p></form><section aria-live="polite" className="mt-8">{error ? <p role="alert" className={`${PANEL} text-sm text-red-300`}>{error}</p> : facilities === null ? <div className={PANEL}><ResultPlaceholder>Search official nursing-home provider records. Published staffing data is research context, not proof that a facility needs an agency.</ResultPlaceholder></div> : facilities.length === 0 ? <div className={PANEL}><ResultPlaceholder>{note || "No matching CMS records were found."}</ResultPlaceholder></div> : <div className="overflow-x-auto rounded-xl border border-white/[0.09]"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-white/[0.05] text-foreground/70"><tr>{["Facility", "Location", "Beds", "Ownership", "Overall", "Staffing", "Nurse turnover"].map((label) => <th key={label} className="p-4">{label}</th>)}</tr></thead><tbody className="divide-y divide-white/[0.07]">{facilities.map((facility) => <tr key={facility.ccn}><td className="p-4 font-bold">{facility.name}<span className="mt-1 block text-xs font-normal text-foreground/45">CCN {facility.ccn}</span></td><td className="p-4">{facility.city}, {facility.state}</td><td className="p-4">{facility.beds ?? "Not published"}</td><td className="p-4">{facility.ownership || "Not published"}</td><td className="p-4">{facility.overallRating ?? "Not published"}</td><td className="p-4">{facility.staffingRating ?? "Not published"}</td><td className="p-4">{facility.nurseTurnover == null ? "Not published" : `${facility.nurseTurnover}%`}</td></tr>)}</tbody></table></div>}<p className="mt-4 text-xs text-foreground/50">Source: <SourceLink href="https://data.cms.gov/provider-data/dataset/4pq5-n9py" asset="cms-healthcare-staffing-explorer">CMS Provider Information</SourceLink>. CMS updates the dataset independently of Muditek.</p></section></div>;
}
