"use client";

import { useState, type FormEvent, type ReactNode } from "react";
import { TrackedSourceLink } from "@/components/acquisition-tracking";
import { useToolTracking } from "@/components/tools/use-tool-tracking";
import { parseMessageHeaders, type HeaderVerdict } from "@/lib/tools/later/email-header";
import { identifyMailProvider, type MailProviderMatch } from "@/lib/tools/later/mail-provider";
import { buildEmailAuthenticationSetup, type MailPlatform } from "@/lib/tools/later/email-setup";
import { calculateMarketRunway, planColdEmailInfrastructure, type InfrastructurePlan } from "@/lib/tools/later/planners";
import { diagnoseOutboundCohort, gradeSignalEvidence, type FunnelCohort } from "@/lib/tools/later/diagnostics";

const FIELD = "mt-2 min-h-11 w-full rounded-[10px] border border-white/[0.14] bg-white/[0.035] px-3 py-2.5 text-sm text-foreground outline-none focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-primary/35";
const LABEL = "text-sm font-bold text-foreground/80";
const BUTTON = "min-h-12 bg-primary px-6 py-3 text-sm font-black text-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-foreground focus-visible:ring-offset-4 focus-visible:ring-offset-background disabled:opacity-50";
const PANEL = "rounded-xl border border-white/[0.09] bg-card/55 p-5 md:p-8";

function Grid({ children }: { children: ReactNode }) { return <div className="grid gap-8 lg:grid-cols-2">{children}</div>; }
function Empty({ children }: { children: ReactNode }) { return <p className="text-sm leading-6 text-foreground/60">{children}</p>; }
function Source({ href, asset, children }: { href: string; asset: string; children: ReactNode }) { return <TrackedSourceLink href={href} asset={asset} placement="tool-result-source" className="text-primary underline underline-offset-4">{children}</TrackedSourceLink>; }

export function EmailHeaderAnalyzer() {
  const [headers, setHeaders] = useState("");
  const [results, setResults] = useState<HeaderVerdict[] | null>(null);
  const tracking = useToolTracking("email-header-analyzer");
  function submit(event: FormEvent) { event.preventDefault(); setResults(parseMessageHeaders(headers)); tracking.complete(); }
  return <Grid><form onSubmit={submit} onChange={tracking.start} className={PANEL}><label className={LABEL}>Raw message headers<textarea className={`${FIELD} min-h-72 font-mono text-xs`} value={headers} onChange={(event) => setHeaders(event.target.value)} required placeholder="Paste the full raw header block" /></label><button className={`${BUTTON} mt-6`}>Read receiver verdicts</button><p className="mt-4 text-xs leading-5 text-foreground/50">Parsing happens in this browser. The tool reports what receiving systems wrote in Authentication-Results and Received-SPF. It does not run a new check.</p></form><section aria-live="polite" className={PANEL}><h2 className="text-2xl font-black">Reported verdicts</h2><div className="mt-5 space-y-4">{results === null ? <Empty>Paste headers to extract existing SPF, DKIM, and DMARC verdicts.</Empty> : results.length === 0 ? <Empty>No supported receiver verdict was found. This does not mean authentication passed or failed.</Empty> : results.map((result, index) => <article key={`${result.source}-${result.mechanism}-${index}`} className="border-t border-white/[0.09] pt-4 first:border-0 first:pt-0"><p className="font-bold uppercase">{result.mechanism}: {result.verdict}</p><p className="mt-2 text-xs text-foreground/55">Header: {result.source}{result.receiver ? ` · Receiver: ${result.receiver}` : ""}</p></article>)}</div></section></Grid>;
}

type MxPayload = { records?: string[]; error?: string; found?: boolean };
export function MailProviderLookup() {
  const [domain, setDomain] = useState(""); const [result, setResult] = useState<MailProviderMatch | "unknown" | null>(null); const [records, setRecords] = useState<string[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const tracking = useToolTracking("mail-provider-lookup");
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); setResult(null); tracking.start(); try { const response = await fetch(`/api/tools/dns?type=mx&domain=${encodeURIComponent(domain)}`); const payload = await response.json() as MxPayload; if (!response.ok || payload.error) { setError(payload.error || "The DNS request failed."); return; } const nextRecords = payload.records ?? []; setRecords(nextRecords); setResult(identifyMailProvider(nextRecords) ?? "unknown"); tracking.complete(); } catch { setError("The DNS request failed. Try again."); } finally { setLoading(false); } }
  return <Grid><form onSubmit={submit} className={PANEL}><label className={LABEL}>Domain<input className={FIELD} value={domain} onChange={(event) => setDomain(event.target.value)} placeholder="example.com" required /></label><button className={`${BUTTON} mt-6`} disabled={loading}>{loading ? "Checking…" : "Look up MX provider"}</button><p className="mt-4 text-xs leading-5 text-foreground/50">The domain is sent to the existing stateless DNS endpoint. The result is a suffix match, not proof of the complete sending stack.</p></form><section aria-live="polite" className={PANEL}><h2 className="text-2xl font-black">MX result</h2><div className="mt-5">{error ? <p role="alert" className="text-sm text-red-300">{error}</p> : result === null ? <Empty>Enter a domain to inspect its public MX records.</Empty> : result === "unknown" ? <><p className="font-bold">Provider unknown</p><p className="mt-3 text-sm leading-6 text-foreground/60">The published MX host did not match the tool&apos;s sourced provider map. No provider is guessed.</p></> : <><p className="text-xl font-black">{result.provider}</p><p className="mt-2 text-sm text-foreground/60">Matched host: {result.matchedHost}</p><p className="mt-3 text-sm"><Source href={result.sourceUrl} asset="mail-provider-lookup">Provider DNS source</Source></p></>}{records.length ? <pre className="mt-5 whitespace-pre-wrap break-all rounded-lg bg-black/25 p-4 text-xs">{records.join("\n")}</pre> : null}</div></section></Grid>;
}

function EmailAuthenticationSetup({ platform, slug }: { platform: MailPlatform; slug: string }) {
  const [policy, setPolicy] = useState<"" | "none" | "quarantine" | "reject">(""); const [reportEmail, setReportEmail] = useState(""); const [result, setResult] = useState<ReturnType<typeof buildEmailAuthenticationSetup> | null>(null); const tracking = useToolTracking(slug);
  function submit(event: FormEvent) { event.preventDefault(); if (!policy) return; setResult(buildEmailAuthenticationSetup(platform, policy, reportEmail)); tracking.complete(); }
  return <Grid><form onSubmit={submit} onChange={tracking.start} className={PANEL}><label className={LABEL}>DMARC policy<select className={FIELD} value={policy} onChange={(event) => setPolicy(event.target.value as typeof policy)} required><option value="">Choose a policy</option><option value="none">Monitor: none</option><option value="quarantine">Quarantine</option><option value="reject">Reject</option></select></label><label className={`${LABEL} mt-5 block`}>Aggregate report email (optional)<input type="email" className={FIELD} value={reportEmail} onChange={(event) => setReportEmail(event.target.value)} placeholder="reports@example.com" /></label><button className={`${BUTTON} mt-6`} disabled={!policy}>Build setup checklist</button><p className="mt-4 text-xs leading-5 text-foreground/50">The SPF value shown covers the named platform only. Inventory every sender before changing DNS. Do not publish a second SPF record.</p></form><section aria-live="polite" className={PANEL}><h2 className="text-2xl font-black">Configuration</h2>{!result ? <div className="mt-5"><Empty>Choose the policy your administrator has approved. No enforcement policy is selected for you.</Empty></div> : <div className="mt-5 space-y-5"><div><h3 className="font-bold">SPF reference</h3><pre className="mt-2 whitespace-pre-wrap break-all rounded-lg bg-black/25 p-4 text-xs">{result.spf}</pre></div><div><h3 className="font-bold">DMARC value</h3><pre className="mt-2 whitespace-pre-wrap break-all rounded-lg bg-black/25 p-4 text-xs">{result.dmarc}</pre></div><ol className="list-decimal space-y-3 pl-5 text-sm leading-6 text-foreground/70">{result.checklist.map((item) => <li key={item}>{item}</li>)}</ol><p className="flex flex-wrap gap-4 text-sm"><Source href={result.sourceUrl} asset={slug}>Official SPF guide</Source><Source href={result.dmarcSourceUrl} asset={slug}>Official DMARC guide</Source></p></div>}</section></Grid>;
}
export function GoogleWorkspaceEmailAuthenticationSetup() { return <EmailAuthenticationSetup platform="google-workspace" slug="google-workspace-email-authentication-setup" />; }
export function Microsoft365EmailAuthenticationSetup() { return <EmailAuthenticationSetup platform="microsoft-365" slug="microsoft-365-email-authentication-setup" />; }

const INFRA_FIELDS = [
  ["dailyNewProspects", "Daily new prospects"], ["sequenceSteps", "Messages per prospect"], ["sendingDaysPerMonth", "Sending days per month"], ["safeEmailsPerMailboxPerDay", "Your emails per mailbox per day"], ["spareCapacityPercent", "Spare capacity"], ["inboxesPerDomain", "Your inboxes per domain"], ["mailboxMonthlyPrice", "Monthly price per mailbox"], ["domainAnnualPrice", "Annual price per domain"],
] as const;
export function ColdEmailInfrastructurePlanner() {
  const [values, setValues] = useState<Record<(typeof INFRA_FIELDS)[number][0], string>>(Object.fromEntries(INFRA_FIELDS.map(([key]) => [key, ""])) as Record<(typeof INFRA_FIELDS)[number][0], string>); const [result, setResult] = useState<InfrastructurePlan | null>(null); const [error, setError] = useState(""); const tracking = useToolTracking("cold-email-infrastructure-planner");
  function submit(event: FormEvent) { event.preventDefault(); const plan = planColdEmailInfrastructure(Object.fromEntries(Object.entries(values).map(([key, value]) => [key, Number(value)])) as Parameters<typeof planColdEmailInfrastructure>[0]); if (!plan) { setError("Enter valid positive capacity values. Spare capacity must stay below 100%."); setResult(null); return; } setError(""); setResult(plan); tracking.complete(); }
  return <Grid><form onSubmit={submit} onChange={tracking.start} className={PANEL}><div className="grid gap-5 sm:grid-cols-2">{INFRA_FIELDS.map(([key, label]) => <label key={key} className={LABEL}>{label}{key === "spareCapacityPercent" ? " (%)" : ""}<input type="number" min="0" step="any" className={FIELD} value={values[key]} onChange={(event) => setValues((current) => ({ ...current, [key]: event.target.value }))} required /></label>)}</div><button className={`${BUTTON} mt-6`}>Calculate capacity</button>{error ? <p role="alert" className="mt-4 text-sm text-red-300">{error}</p> : null}</form><section aria-live="polite" className={PANEL}><h2 className="text-2xl font-black">Capacity plan</h2>{!result ? <div className="mt-5"><Empty>Every capacity and price assumption comes from you. The tool contains no safe-sending benchmark.</Empty></div> : <dl className="mt-5 space-y-4">{[["Monthly sequence emails", result.monthlyEmails.toLocaleString()], ["Average daily emails", result.averageDailyEmails.toLocaleString()], ["Required daily capacity", result.requiredDailyCapacity.toLocaleString()], ["Mailboxes", result.mailboxes], ["Domains", result.domains], ["Estimated monthly cost", result.estimatedMonthlyCost.toFixed(2)]].map(([label, value]) => <div key={label} className="border-t border-white/[0.09] pt-4"><dt className="text-sm text-foreground/55">{label}</dt><dd className="mt-1 text-2xl font-black">{value}</dd></div>)}</dl>}</section></Grid>;
}

const RUNWAY_FIELDS = [["totalEligibleAccounts", "Total eligible accounts"], ["excludedAccounts", "Excluded accounts"], ["accountsAlreadyActivated", "Accounts already activated"], ["newAccountsActivatedPerPeriod", "New accounts activated per period"]] as const;
export function OutboundMarketRunwayCalculator() {
  const [values, setValues] = useState<Record<(typeof RUNWAY_FIELDS)[number][0], string>>(Object.fromEntries(RUNWAY_FIELDS.map(([key]) => [key, ""])) as Record<(typeof RUNWAY_FIELDS)[number][0], string>); const [period, setPeriod] = useState(""); const [result, setResult] = useState<ReturnType<typeof calculateMarketRunway>>(null); const [error, setError] = useState(""); const tracking = useToolTracking("outbound-market-runway-calculator");
  function submit(event: FormEvent) { event.preventDefault(); const next = calculateMarketRunway(Object.fromEntries(Object.entries(values).map(([key, value]) => [key, Number(value)])) as Parameters<typeof calculateMarketRunway>[0]); if (!next || !period.trim()) { setError("Enter a period and counts that do not exceed the eligible market."); setResult(null); return; } setError(""); setResult(next); tracking.complete(); }
  return <Grid><form onSubmit={submit} onChange={tracking.start} className={PANEL}><div className="grid gap-5">{RUNWAY_FIELDS.map(([key, label]) => <label key={key} className={LABEL}>{label}<input type="number" min="0" className={FIELD} value={values[key]} onChange={(event) => setValues((current) => ({ ...current, [key]: event.target.value }))} required /></label>)}<label className={LABEL}>Period name<input className={FIELD} value={period} onChange={(event) => setPeriod(event.target.value)} placeholder="week or month" required /></label></div><button className={`${BUTTON} mt-6`}>Calculate runway</button>{error ? <p role="alert" className="mt-4 text-sm text-red-300">{error}</p> : null}</form><section aria-live="polite" className={PANEL}><h2 className="text-2xl font-black">Reachable market runway</h2>{!result ? <div className="mt-5"><Empty>Use one deduplicated market definition and one activation period.</Empty></div> : <div className="mt-5"><p className="text-5xl font-black">{result.exactPeriods.toFixed(1)} {period}{result.exactPeriods === 1 ? "" : "s"}</p><p className="mt-4 text-sm leading-6 text-foreground/65">{result.reachableAccounts.toLocaleString()} accounts remain. {result.fullPeriods} full {period}{result.fullPeriods === 1 ? "" : "s"} fit at the stated activation rate{result.finalPeriodAccounts ? `, with ${result.finalPeriodAccounts} accounts left for the final partial period` : ""}.</p></div>}</section></Grid>;
}

export function SignalEvidenceGrader() {
  const [sourceUrl, setSourceUrl] = useState(""); const [observedDate, setObservedDate] = useState(""); const [flags, setFlags] = useState({ namedAccount: false, directSource: false, factIsExplicit: false, withinResearchWindow: false, contradictoryEvidence: false }); const [result, setResult] = useState<ReturnType<typeof gradeSignalEvidence> | null>(null); const tracking = useToolTracking("signal-evidence-grader");
  const checks: Array<[keyof typeof flags, string]> = [["namedAccount", "The source names the exact account."], ["directSource", "This is the original or authoritative source."], ["factIsExplicit", "The fact is stated directly, not inferred."], ["withinResearchWindow", "The date is inside our written research window."], ["contradictoryEvidence", "I found contradictory evidence."]];
  function submit(event: FormEvent) { event.preventDefault(); setResult(gradeSignalEvidence({ sourceUrl, observedDate, ...flags })); tracking.complete(); }
  return <Grid><form onSubmit={submit} onChange={tracking.start} className={PANEL}><label className={LABEL}>Public source URL<input type="url" className={FIELD} value={sourceUrl} onChange={(event) => setSourceUrl(event.target.value)} required /></label><label className={`${LABEL} mt-5 block`}>Date observed<input type="date" className={FIELD} value={observedDate} onChange={(event) => setObservedDate(event.target.value)} required /></label><fieldset className="mt-6 space-y-3"><legend className="font-bold">Evidence checks</legend>{checks.map(([key, label]) => <label key={key} className="flex min-h-11 items-center gap-3 border border-white/[0.1] p-3 text-sm"><input type="checkbox" checked={flags[key]} onChange={(event) => setFlags((current) => ({ ...current, [key]: event.target.checked }))} />{label}</label>)}</fieldset><button className={`${BUTTON} mt-6`}>Check evidence</button></form><section aria-live="polite" className={PANEL}><h2 className="text-2xl font-black">Evidence status</h2>{!result ? <div className="mt-5"><Empty>This checks whether a public fact is usable for account prioritization. It never produces an intent score.</Empty></div> : <div className="mt-5"><p className="text-2xl font-black capitalize">{result.status.replaceAll("-", " ")}</p><p className="mt-4 text-sm leading-6 text-foreground/70">{result.statement}</p>{result.missing.length ? <><h3 className="mt-6 font-bold">Resolve before use</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-foreground/65">{result.missing.map((item) => <li key={item}>{item}</li>)}</ul></> : null}</div>}</section></Grid>;
}

const COHORT_FIELDS: Array<[keyof FunnelCohort, string]> = [["qualifiedContactsReached", "Qualified contacts reached"], ["delivered", "Delivered messages"], ["positiveReplies", "Positive replies"], ["callsBooked", "Calls booked"], ["callsHeld", "Calls held"], ["qualifiedCallsHeld", "Qualified calls held"], ["proposals", "Proposals"], ["clients", "Clients"]];
export function OutboundFailureDiagnostic() {
  const [values, setValues] = useState<Record<keyof FunnelCohort, string>>(Object.fromEntries(COHORT_FIELDS.map(([key]) => [key, ""])) as Record<keyof FunnelCohort, string>); const [result, setResult] = useState<ReturnType<typeof diagnoseOutboundCohort> | null>(null); const tracking = useToolTracking("outbound-failure-diagnostic");
  function submit(event: FormEvent) { event.preventDefault(); setResult(diagnoseOutboundCohort(Object.fromEntries(Object.entries(values).map(([key, value]) => [key, Number(value)])) as FunnelCohort)); tracking.complete(); }
  return <Grid><form onSubmit={submit} onChange={tracking.start} className={PANEL}><p className="mb-6 text-sm leading-6 text-foreground/60">Use one fixed cohort. Do not mix contacts from one period with outcomes from another.</p><div className="grid gap-5 sm:grid-cols-2">{COHORT_FIELDS.map(([key, label]) => <label key={key} className={LABEL}>{label}<input type="number" min="0" className={FIELD} value={values[key]} onChange={(event) => setValues((current) => ({ ...current, [key]: event.target.value }))} required /></label>)}</div><button className={`${BUTTON} mt-6`}>Find the first break</button></form><section aria-live="polite" className={PANEL}><h2 className="text-2xl font-black">Cohort diagnosis</h2>{!result ? <div className="mt-5"><Empty>The tool reports the first complete break in the measured funnel. It does not guess the cause.</Empty></div> : "error" in result ? <p role="alert" className="mt-5 text-sm text-red-300">{result.error}</p> : <div className="mt-5"><p className="text-xl font-black">{result.finding}</p>{"transitions" in result && result.transitions ? <dl className="mt-6 space-y-3">{result.transitions.map((transition) => <div key={transition.label} className="flex justify-between gap-4 border-t border-white/[0.09] pt-3 text-sm"><dt>{transition.label}</dt><dd className="font-bold">{(transition.rate * 100).toFixed(1)}%</dd></div>)}</dl> : null}</div>}</section></Grid>;
}
